// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmerror_data.proto

/*
Package cmerror_data is a generated protocol buffer package.

It is generated from these files:
	cmerror_data.proto

It has these top-level messages:
	ErrorData
	CmerrorData
*/
package cmerror_data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorData struct {
	Identifier        *string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Count             *uint64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	LastUpdated       *uint64 `protobuf:"varint,3,opt,name=last_updated" json:"last_updated,omitempty"`
	IsEnabled         *bool   `protobuf:"varint,4,opt,name=is_enabled" json:"is_enabled,omitempty"`
	ModuleId          *uint32 `protobuf:"varint,5,opt,name=module_id" json:"module_id,omitempty"`
	ComponentId       *uint32 `protobuf:"varint,6,opt,name=component_id" json:"component_id,omitempty"`
	ErrorCode         *uint32 `protobuf:"varint,7,opt,name=error_code" json:"error_code,omitempty"`
	ErrorSourceType   *string `protobuf:"bytes,8,opt,name=error_source_type" json:"error_source_type,omitempty"`
	OccurCount        *uint32 `protobuf:"varint,9,opt,name=occur_count" json:"occur_count,omitempty"`
	ClearedCount      *uint32 `protobuf:"varint,10,opt,name=cleared_count" json:"cleared_count,omitempty"`
	LastClearedAt     *uint64 `protobuf:"varint,11,opt,name=last_cleared_at" json:"last_cleared_at,omitempty"`
	ActionCount       *uint32 `protobuf:"varint,12,opt,name=action_count" json:"action_count,omitempty"`
	LastActionTakenAt *uint64 `protobuf:"varint,13,opt,name=last_action_taken_at" json:"last_action_taken_at,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *ErrorData) Reset()                    { *m = ErrorData{} }
func (m *ErrorData) String() string            { return proto.CompactTextString(m) }
func (*ErrorData) ProtoMessage()               {}
func (*ErrorData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ErrorData) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *ErrorData) GetCount() uint64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ErrorData) GetLastUpdated() uint64 {
	if m != nil && m.LastUpdated != nil {
		return *m.LastUpdated
	}
	return 0
}

func (m *ErrorData) GetIsEnabled() bool {
	if m != nil && m.IsEnabled != nil {
		return *m.IsEnabled
	}
	return false
}

func (m *ErrorData) GetModuleId() uint32 {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return 0
}

func (m *ErrorData) GetComponentId() uint32 {
	if m != nil && m.ComponentId != nil {
		return *m.ComponentId
	}
	return 0
}

func (m *ErrorData) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *ErrorData) GetErrorSourceType() string {
	if m != nil && m.ErrorSourceType != nil {
		return *m.ErrorSourceType
	}
	return ""
}

func (m *ErrorData) GetOccurCount() uint32 {
	if m != nil && m.OccurCount != nil {
		return *m.OccurCount
	}
	return 0
}

func (m *ErrorData) GetClearedCount() uint32 {
	if m != nil && m.ClearedCount != nil {
		return *m.ClearedCount
	}
	return 0
}

func (m *ErrorData) GetLastClearedAt() uint64 {
	if m != nil && m.LastClearedAt != nil {
		return *m.LastClearedAt
	}
	return 0
}

func (m *ErrorData) GetActionCount() uint32 {
	if m != nil && m.ActionCount != nil {
		return *m.ActionCount
	}
	return 0
}

func (m *ErrorData) GetLastActionTakenAt() uint64 {
	if m != nil && m.LastActionTakenAt != nil {
		return *m.LastActionTakenAt
	}
	return 0
}

type CmerrorData struct {
	ErrorItem        []*ErrorData `protobuf:"bytes,1,rep,name=error_item" json:"error_item,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CmerrorData) Reset()                    { *m = CmerrorData{} }
func (m *CmerrorData) String() string            { return proto.CompactTextString(m) }
func (*CmerrorData) ProtoMessage()               {}
func (*CmerrorData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CmerrorData) GetErrorItem() []*ErrorData {
	if m != nil {
		return m.ErrorItem
	}
	return nil
}

var E_JnprCmerrorDataExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*CmerrorData)(nil),
	Field:         21,
	Name:          "jnpr_cmerror_data_ext",
	Tag:           "bytes,21,opt,name=jnpr_cmerror_data_ext",
	Filename:      "cmerror_data.proto",
}

func init() {
	proto.RegisterType((*ErrorData)(nil), "ErrorData")
	proto.RegisterType((*CmerrorData)(nil), "CmerrorData")
	proto.RegisterExtension(E_JnprCmerrorDataExt)
}

func init() { proto.RegisterFile("cmerror_data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x3f, 0x6f, 0xdb, 0x30,
	0x10, 0xc5, 0x41, 0xff, 0x69, 0xad, 0x93, 0x8c, 0xd6, 0xac, 0x8d, 0xd2, 0x76, 0x61, 0x08, 0xee,
	0xa2, 0xa5, 0x1a, 0x3c, 0x76, 0x2a, 0x5a, 0x77, 0xc9, 0x90, 0x25, 0x1f, 0x80, 0x60, 0xc8, 0x0b,
	0xc0, 0x58, 0x22, 0x05, 0xea, 0x84, 0xc4, 0x6b, 0xbe, 0x69, 0xbe, 0x49, 0x20, 0xc9, 0x36, 0xb4,
	0xfe, 0xee, 0xdd, 0xf1, 0x3d, 0x3e, 0xe0, 0xba, 0xc4, 0x10, 0x7c, 0x90, 0x46, 0x91, 0xca, 0xab,
	0xe0, 0xc9, 0x6f, 0xbe, 0x11, 0x16, 0x58, 0x22, 0x85, 0xb3, 0x24, 0x5f, 0xf5, 0x70, 0xff, 0x3e,
	0x82, 0xe8, 0x7f, 0xab, 0x3c, 0x2a, 0x52, 0x7c, 0x0d, 0x60, 0x0d, 0x3a, 0xb2, 0x4f, 0x16, 0x83,
	0x60, 0x29, 0xcb, 0xa2, 0xbf, 0xd3, 0xb7, 0x3f, 0xa3, 0x19, 0xe3, 0x4b, 0x98, 0x6a, 0xdf, 0x38,
	0x12, 0xa3, 0x94, 0x65, 0x93, 0x8e, 0x0a, 0xc6, 0xb7, 0x90, 0x14, 0xaa, 0x26, 0xd9, 0x54, 0x46,
	0x11, 0x1a, 0x31, 0xbe, 0x0d, 0xbf, 0x32, 0xce, 0x01, 0x6c, 0x2d, 0xd1, 0xa9, 0xc7, 0x02, 0x8d,
	0x98, 0xa4, 0x2c, 0x9b, 0xf1, 0x05, 0x44, 0xa5, 0x37, 0x4d, 0x81, 0xd2, 0x1a, 0x31, 0x4d, 0x59,
	0x36, 0xe7, 0x4b, 0x48, 0xb4, 0x2f, 0x2b, 0xef, 0xd0, 0x51, 0x4b, 0x3f, 0x75, 0x94, 0x03, 0xf4,
	0x09, 0xb4, 0x37, 0x28, 0x3e, 0x77, 0x6c, 0x0d, 0x8b, 0x9e, 0xd5, 0xbe, 0x09, 0x1a, 0x25, 0x9d,
	0x2b, 0x14, 0xb3, 0xd6, 0x25, 0xdf, 0x40, 0xec, 0xb5, 0x6e, 0x5a, 0x79, 0x6b, 0x32, 0x6a, 0xf5,
	0x57, 0x93, 0x3f, 0x60, 0xae, 0x0b, 0x54, 0x01, 0xcd, 0x65, 0x0a, 0xc3, 0xe9, 0x0e, 0xbe, 0x74,
	0x11, 0xae, 0x12, 0x45, 0x22, 0x1e, 0xa6, 0xd8, 0x42, 0xa2, 0x34, 0x59, 0xef, 0x2e, 0xcb, 0xc9,
	0x70, 0xf9, 0x27, 0x2c, 0xbb, 0xe5, 0x8b, 0x82, 0xd4, 0x09, 0x5d, 0x7b, 0x61, 0x3e, 0xb8, 0xb0,
	0xff, 0x05, 0xf1, 0xbf, 0xbe, 0x8e, 0xee, 0x93, 0x77, 0xd7, 0x64, 0x96, 0xb0, 0x14, 0x2c, 0x1d,
	0x67, 0xf1, 0x01, 0xf2, 0x5b, 0x09, 0xbf, 0x8f, 0xb0, 0x7a, 0x76, 0x55, 0x90, 0xc3, 0x0a, 0x25,
	0xbe, 0x12, 0xff, 0x9e, 0xdf, 0x35, 0xce, 0x56, 0x18, 0xee, 0x91, 0x5e, 0x7c, 0x38, 0xd5, 0x0f,
	0xe8, 0x6a, 0x1f, 0x6a, 0xb1, 0x4a, 0x59, 0x16, 0x1f, 0x92, 0x7c, 0xf0, 0xca, 0x47, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xeb, 0x10, 0x5a, 0xbe, 0x02, 0x02, 0x00, 0x00,
}
