// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmerror.proto

/*
Package cmerror is a generated protocol buffer package.

It is generated from these files:
	cmerror.proto

It has these top-level messages:
	Error
	Cmerror
*/
package cmerror

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Identifier        *string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
	Description       *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Help              *string `protobuf:"bytes,3,opt,name=help" json:"help,omitempty"`
	Scope             *string `protobuf:"bytes,4,opt,name=scope" json:"scope,omitempty"`
	Category          *string `protobuf:"bytes,5,opt,name=category" json:"category,omitempty"`
	Action            *uint32 `protobuf:"varint,6,opt,name=action" json:"action,omitempty"`
	Severity          *string `protobuf:"bytes,7,opt,name=severity" json:"severity,omitempty"`
	Threshold         *uint32 `protobuf:"varint,8,opt,name=threshold" json:"threshold,omitempty"`
	Limit             *uint32 `protobuf:"varint,9,opt,name=limit" json:"limit,omitempty"`
	RaisingThreshold  *uint32 `protobuf:"varint,10,opt,name=raising_threshold" json:"raising_threshold,omitempty"`
	ClearingThreshold *uint32 `protobuf:"varint,11,opt,name=clearing_threshold" json:"clearing_threshold,omitempty"`
	ModuleId          *uint32 `protobuf:"varint,12,opt,name=module_id" json:"module_id,omitempty"`
	ComponentId       *uint32 `protobuf:"varint,13,opt,name=component_id" json:"component_id,omitempty"`
	ErrorCode         *uint32 `protobuf:"varint,14,opt,name=error_code" json:"error_code,omitempty"`
	ErrorSourceType   *string `protobuf:"bytes,15,opt,name=error_source_type" json:"error_source_type,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *Error) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Error) GetHelp() string {
	if m != nil && m.Help != nil {
		return *m.Help
	}
	return ""
}

func (m *Error) GetScope() string {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return ""
}

func (m *Error) GetCategory() string {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return ""
}

func (m *Error) GetAction() uint32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

func (m *Error) GetSeverity() string {
	if m != nil && m.Severity != nil {
		return *m.Severity
	}
	return ""
}

func (m *Error) GetThreshold() uint32 {
	if m != nil && m.Threshold != nil {
		return *m.Threshold
	}
	return 0
}

func (m *Error) GetLimit() uint32 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *Error) GetRaisingThreshold() uint32 {
	if m != nil && m.RaisingThreshold != nil {
		return *m.RaisingThreshold
	}
	return 0
}

func (m *Error) GetClearingThreshold() uint32 {
	if m != nil && m.ClearingThreshold != nil {
		return *m.ClearingThreshold
	}
	return 0
}

func (m *Error) GetModuleId() uint32 {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return 0
}

func (m *Error) GetComponentId() uint32 {
	if m != nil && m.ComponentId != nil {
		return *m.ComponentId
	}
	return 0
}

func (m *Error) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *Error) GetErrorSourceType() string {
	if m != nil && m.ErrorSourceType != nil {
		return *m.ErrorSourceType
	}
	return ""
}

type Cmerror struct {
	ErrorItem        []*Error `protobuf:"bytes,1,rep,name=error_item" json:"error_item,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Cmerror) Reset()                    { *m = Cmerror{} }
func (m *Cmerror) String() string            { return proto.CompactTextString(m) }
func (*Cmerror) ProtoMessage()               {}
func (*Cmerror) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Cmerror) GetErrorItem() []*Error {
	if m != nil {
		return m.ErrorItem
	}
	return nil
}

var E_JnprCmerrorExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*Cmerror)(nil),
	Field:         20,
	Name:          "jnpr_cmerror_ext",
	Tag:           "bytes,20,opt,name=jnpr_cmerror_ext",
	Filename:      "cmerror.proto",
}

func init() {
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*Cmerror)(nil), "Cmerror")
	proto.RegisterExtension(E_JnprCmerrorExt)
}

func init() { proto.RegisterFile("cmerror.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x6e, 0xe2, 0x30,
	0x10, 0x86, 0x15, 0x20, 0x90, 0x4c, 0x08, 0x0b, 0x01, 0x69, 0x0d, 0xa7, 0x08, 0x69, 0xa5, 0x9c,
	0x72, 0xe0, 0xb8, 0x7b, 0x59, 0xed, 0x6a, 0x2f, 0x7b, 0xe8, 0xa5, 0x0f, 0x10, 0x45, 0xce, 0x14,
	0xdc, 0x26, 0xb6, 0x35, 0x1e, 0xda, 0xe6, 0xda, 0xb7, 0xea, 0xdb, 0x55, 0x31, 0xa0, 0xaa, 0xc7,
	0xf9, 0xfe, 0x6f, 0x6c, 0xeb, 0x37, 0xa4, 0xb2, 0x43, 0x22, 0x43, 0xa5, 0x25, 0xc3, 0x66, 0xb7,
	0x66, 0x6c, 0xb1, 0x43, 0xa6, 0xbe, 0x62, 0x63, 0x2f, 0x70, 0xff, 0x3e, 0x82, 0xf0, 0xdf, 0x20,
	0x65, 0x5b, 0x00, 0xd5, 0xa0, 0x66, 0xf5, 0xa0, 0x90, 0x44, 0x90, 0x07, 0x45, 0xfc, 0x27, 0x7c,
	0xfb, 0x3d, 0x8a, 0x82, 0x6c, 0x0d, 0x49, 0x83, 0x4e, 0x92, 0xb2, 0xac, 0x8c, 0x16, 0xa3, 0x21,
	0xcb, 0xe6, 0x30, 0x39, 0x61, 0x6b, 0xc5, 0xd8, 0x4f, 0x29, 0x84, 0x4e, 0x1a, 0x8b, 0x62, 0xe2,
	0xc7, 0x25, 0x44, 0xb2, 0x66, 0x3c, 0x1a, 0xea, 0x45, 0xe8, 0xc9, 0x02, 0xa6, 0xb5, 0xf4, 0xeb,
	0xd3, 0x3c, 0x28, 0xd2, 0xc1, 0x70, 0xf8, 0x8c, 0xa4, 0xb8, 0x17, 0x33, 0x6f, 0xac, 0x20, 0xe6,
	0x13, 0xa1, 0x3b, 0x99, 0xb6, 0x11, 0x91, 0x97, 0x52, 0x08, 0x5b, 0xd5, 0x29, 0x16, 0xb1, 0x1f,
	0xb7, 0xb0, 0xa2, 0x5a, 0x39, 0xa5, 0x8f, 0xd5, 0xa7, 0x09, 0x3e, 0xda, 0x41, 0x26, 0x5b, 0xac,
	0xe9, 0x6b, 0x96, 0xf8, 0x6c, 0x05, 0x71, 0x67, 0x9a, 0x73, 0x8b, 0x95, 0x6a, 0xc4, 0xdc, 0xa3,
	0x0d, 0xcc, 0xa5, 0xe9, 0xac, 0xd1, 0xa8, 0x79, 0xa0, 0xa9, 0xa7, 0x19, 0x80, 0x2f, 0xac, 0x92,
	0xa6, 0x41, 0xb1, 0xb8, 0xdd, 0x79, 0x61, 0xce, 0x9c, 0x49, 0x62, 0xc5, 0xbd, 0x45, 0xf1, 0x6d,
	0x78, 0xf0, 0xfe, 0x07, 0xcc, 0xfe, 0x5e, 0x1a, 0xce, 0x76, 0xb7, 0x4d, 0xc5, 0xd8, 0x89, 0x20,
	0x1f, 0x17, 0xc9, 0x61, 0x5a, 0xfa, 0x62, 0x7f, 0xfe, 0x82, 0xe5, 0xa3, 0xb6, 0x54, 0x5d, 0x7f,
	0xa3, 0xc2, 0x57, 0xce, 0xbe, 0x97, 0xff, 0xcf, 0x5a, 0x59, 0xa4, 0x3b, 0xe4, 0x17, 0x43, 0x4f,
	0xee, 0x1e, 0xb5, 0x33, 0xe4, 0xc4, 0x26, 0x0f, 0x8a, 0xe4, 0x10, 0x95, 0xd7, 0x83, 0x3f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x38, 0xc9, 0x26, 0x78, 0xc4, 0x01, 0x00, 0x00,
}
