// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cpu_memory_utilization.proto

/*
Package cpu_memory_utilization is a generated protocol buffer package.

It is generated from these files:
	cpu_memory_utilization.proto

It has these top-level messages:
	CpuMemoryUtilization
	CpuMemoryUtilizationSummary
	CpuMemoryUtilizationPerApplication
*/
package cpu_memory_utilization

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CpuMemoryUtilization struct {
	Utilization      []*CpuMemoryUtilizationSummary `protobuf:"bytes,1,rep,name=utilization" json:"utilization,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *CpuMemoryUtilization) Reset()                    { *m = CpuMemoryUtilization{} }
func (m *CpuMemoryUtilization) String() string            { return proto.CompactTextString(m) }
func (*CpuMemoryUtilization) ProtoMessage()               {}
func (*CpuMemoryUtilization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CpuMemoryUtilization) GetUtilization() []*CpuMemoryUtilizationSummary {
	if m != nil {
		return m.Utilization
	}
	return nil
}

type CpuMemoryUtilizationSummary struct {
	Name                   *string                               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Size                   *uint64                               `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	BytesAllocated         *uint64                               `protobuf:"varint,3,opt,name=bytes_allocated" json:"bytes_allocated,omitempty"`
	Utilization            *int32                                `protobuf:"varint,4,opt,name=utilization" json:"utilization,omitempty"`
	ApplicationUtilization []*CpuMemoryUtilizationPerApplication `protobuf:"bytes,5,rep,name=application_utilization" json:"application_utilization,omitempty"`
	XXX_unrecognized       []byte                                `json:"-"`
}

func (m *CpuMemoryUtilizationSummary) Reset()                    { *m = CpuMemoryUtilizationSummary{} }
func (m *CpuMemoryUtilizationSummary) String() string            { return proto.CompactTextString(m) }
func (*CpuMemoryUtilizationSummary) ProtoMessage()               {}
func (*CpuMemoryUtilizationSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CpuMemoryUtilizationSummary) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CpuMemoryUtilizationSummary) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *CpuMemoryUtilizationSummary) GetBytesAllocated() uint64 {
	if m != nil && m.BytesAllocated != nil {
		return *m.BytesAllocated
	}
	return 0
}

func (m *CpuMemoryUtilizationSummary) GetUtilization() int32 {
	if m != nil && m.Utilization != nil {
		return *m.Utilization
	}
	return 0
}

func (m *CpuMemoryUtilizationSummary) GetApplicationUtilization() []*CpuMemoryUtilizationPerApplication {
	if m != nil {
		return m.ApplicationUtilization
	}
	return nil
}

type CpuMemoryUtilizationPerApplication struct {
	Name              *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	BytesAllocated    *uint64 `protobuf:"varint,2,opt,name=bytes_allocated" json:"bytes_allocated,omitempty"`
	Allocations       *uint64 `protobuf:"varint,3,opt,name=allocations" json:"allocations,omitempty"`
	Frees             *uint64 `protobuf:"varint,4,opt,name=frees" json:"frees,omitempty"`
	AllocationsFailed *uint64 `protobuf:"varint,5,opt,name=allocations_failed" json:"allocations_failed,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *CpuMemoryUtilizationPerApplication) Reset()         { *m = CpuMemoryUtilizationPerApplication{} }
func (m *CpuMemoryUtilizationPerApplication) String() string { return proto.CompactTextString(m) }
func (*CpuMemoryUtilizationPerApplication) ProtoMessage()    {}
func (*CpuMemoryUtilizationPerApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

func (m *CpuMemoryUtilizationPerApplication) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CpuMemoryUtilizationPerApplication) GetBytesAllocated() uint64 {
	if m != nil && m.BytesAllocated != nil {
		return *m.BytesAllocated
	}
	return 0
}

func (m *CpuMemoryUtilizationPerApplication) GetAllocations() uint64 {
	if m != nil && m.Allocations != nil {
		return *m.Allocations
	}
	return 0
}

func (m *CpuMemoryUtilizationPerApplication) GetFrees() uint64 {
	if m != nil && m.Frees != nil {
		return *m.Frees
	}
	return 0
}

func (m *CpuMemoryUtilizationPerApplication) GetAllocationsFailed() uint64 {
	if m != nil && m.AllocationsFailed != nil {
		return *m.AllocationsFailed
	}
	return 0
}

var E_CpuMemoryUtilExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*CpuMemoryUtilization)(nil),
	Field:         1,
	Name:          "cpu_memory_util_ext",
	Tag:           "bytes,1,opt,name=cpu_memory_util_ext",
	Filename:      "cpu_memory_utilization.proto",
}

func init() {
	proto.RegisterType((*CpuMemoryUtilization)(nil), "CpuMemoryUtilization")
	proto.RegisterType((*CpuMemoryUtilizationSummary)(nil), "CpuMemoryUtilizationSummary")
	proto.RegisterType((*CpuMemoryUtilizationPerApplication)(nil), "CpuMemoryUtilizationPerApplication")
	proto.RegisterExtension(E_CpuMemoryUtilExt)
}

func init() { proto.RegisterFile("cpu_memory_utilization.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0xc9, 0xd6, 0x1e, 0x7c, 0xa7, 0x08, 0x99, 0xb2, 0x30, 0x77, 0x28, 0xf5, 0xd2, 0x53,
	0xc1, 0x1d, 0xbd, 0x89, 0x5e, 0x54, 0x14, 0x61, 0x78, 0x0e, 0xb1, 0x7b, 0x07, 0xc1, 0xa4, 0x09,
	0x49, 0x8a, 0x76, 0x5f, 0xc1, 0xcf, 0xe2, 0x77, 0x94, 0xc5, 0xc9, 0xea, 0x28, 0x7a, 0xcc, 0xf3,
	0x27, 0xfc, 0x1e, 0x5e, 0x98, 0x55, 0xb6, 0xe1, 0x1a, 0xb5, 0x71, 0x2d, 0x6f, 0x82, 0x54, 0x72,
	0x2d, 0x82, 0x34, 0x75, 0x69, 0x9d, 0x09, 0x66, 0x3a, 0x0e, 0xa8, 0x50, 0x63, 0x70, 0x2d, 0x0f,
	0xc6, 0x7e, 0x8b, 0xf9, 0x2d, 0x9c, 0x5c, 0xdb, 0xe6, 0x21, 0x76, 0x9e, 0x77, 0x15, 0x7a, 0x01,
	0xa3, 0xce, 0x0f, 0x8c, 0x64, 0xc3, 0x62, 0x34, 0x9f, 0x95, 0x7d, 0xd9, 0x45, 0xa3, 0xb5, 0x70,
	0x6d, 0xfe, 0x49, 0xe0, 0xec, 0x0f, 0x9f, 0x1e, 0x42, 0x52, 0x0b, 0x8d, 0x8c, 0x64, 0xa4, 0x38,
	0xd8, 0xbc, 0xbc, 0x5c, 0x23, 0x1b, 0x64, 0xa4, 0x48, 0xe8, 0x04, 0x8e, 0x5f, 0xda, 0x80, 0x9e,
	0x0b, 0xa5, 0x4c, 0x25, 0x02, 0x2e, 0xd9, 0x30, 0x1a, 0xe3, 0xdf, 0x1c, 0x49, 0x46, 0x8a, 0x94,
	0xde, 0xc0, 0x44, 0x58, 0xab, 0x64, 0x15, 0xc5, 0xee, 0x54, 0x96, 0x46, 0xd0, 0xf3, 0x5e, 0xd0,
	0x27, 0x74, 0x57, 0xbb, 0x5a, 0xfe, 0x41, 0x20, 0xff, 0x3f, 0xb6, 0x87, 0xdd, 0x03, 0x3a, 0xf8,
	0x01, 0xdd, 0x4a, 0xd2, 0xd4, 0x7e, 0x4b, 0x7f, 0x04, 0xe9, 0xca, 0x21, 0xfa, 0xc8, 0x9d, 0xd0,
	0x29, 0xd0, 0x4e, 0x86, 0xaf, 0x84, 0x54, 0xb8, 0x64, 0xe9, 0xc6, 0xbb, 0xbc, 0x87, 0xf1, 0xde,
	0xf5, 0x38, 0xbe, 0x07, 0x3a, 0x29, 0xef, 0x9a, 0x5a, 0x5a, 0x74, 0x8f, 0x18, 0xde, 0x8c, 0x7b,
	0xf5, 0x0b, 0xac, 0xbd, 0x71, 0x3e, 0xe2, 0x8c, 0xe6, 0xa7, 0xbd, 0x43, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xf1, 0xf5, 0x64, 0x52, 0x09, 0x02, 0x00, 0x00,
}
