// Code generated by protoc-gen-go. DO NOT EDIT.
// source: firewall.proto

/*
Package firewall is a generated protocol buffer package.

It is generated from these files:
	firewall.proto

It has these top-level messages:
	Firewall
	FirewallStats
	MemoryUsage
	CounterStats
	PolicerStats
	ExtendedPolicerStats
	HierarchicalPolicerStats
*/
package firewall

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Firewall struct {
	FirewallStats    []*FirewallStats `protobuf:"bytes,1,rep,name=firewall_stats" json:"firewall_stats,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Firewall) Reset()                    { *m = Firewall{} }
func (m *Firewall) String() string            { return proto.CompactTextString(m) }
func (*Firewall) ProtoMessage()               {}
func (*Firewall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Firewall) GetFirewallStats() []*FirewallStats {
	if m != nil {
		return m.FirewallStats
	}
	return nil
}

type FirewallStats struct {
	FilterName               *string                     `protobuf:"bytes,1,req,name=filter_name" json:"filter_name,omitempty"`
	Timestamp                *uint64                     `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	MemoryUsage              []*MemoryUsage              `protobuf:"bytes,3,rep,name=memory_usage" json:"memory_usage,omitempty"`
	CounterStats             []*CounterStats             `protobuf:"bytes,4,rep,name=counter_stats" json:"counter_stats,omitempty"`
	PolicerStats             []*PolicerStats             `protobuf:"bytes,5,rep,name=policer_stats" json:"policer_stats,omitempty"`
	HierarchicalPolicerStats []*HierarchicalPolicerStats `protobuf:"bytes,6,rep,name=hierarchical_policer_stats" json:"hierarchical_policer_stats,omitempty"`
	XXX_unrecognized         []byte                      `json:"-"`
}

func (m *FirewallStats) Reset()                    { *m = FirewallStats{} }
func (m *FirewallStats) String() string            { return proto.CompactTextString(m) }
func (*FirewallStats) ProtoMessage()               {}
func (*FirewallStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FirewallStats) GetFilterName() string {
	if m != nil && m.FilterName != nil {
		return *m.FilterName
	}
	return ""
}

func (m *FirewallStats) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *FirewallStats) GetMemoryUsage() []*MemoryUsage {
	if m != nil {
		return m.MemoryUsage
	}
	return nil
}

func (m *FirewallStats) GetCounterStats() []*CounterStats {
	if m != nil {
		return m.CounterStats
	}
	return nil
}

func (m *FirewallStats) GetPolicerStats() []*PolicerStats {
	if m != nil {
		return m.PolicerStats
	}
	return nil
}

func (m *FirewallStats) GetHierarchicalPolicerStats() []*HierarchicalPolicerStats {
	if m != nil {
		return m.HierarchicalPolicerStats
	}
	return nil
}

type MemoryUsage struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Allocated        *uint64 `protobuf:"varint,2,opt,name=allocated" json:"allocated,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MemoryUsage) Reset()                    { *m = MemoryUsage{} }
func (m *MemoryUsage) String() string            { return proto.CompactTextString(m) }
func (*MemoryUsage) ProtoMessage()               {}
func (*MemoryUsage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MemoryUsage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MemoryUsage) GetAllocated() uint64 {
	if m != nil && m.Allocated != nil {
		return *m.Allocated
	}
	return 0
}

type CounterStats struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Packets          *uint64 `protobuf:"varint,2,opt,name=packets" json:"packets,omitempty"`
	Bytes            *uint64 `protobuf:"varint,3,opt,name=bytes" json:"bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CounterStats) Reset()                    { *m = CounterStats{} }
func (m *CounterStats) String() string            { return proto.CompactTextString(m) }
func (*CounterStats) ProtoMessage()               {}
func (*CounterStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CounterStats) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CounterStats) GetPackets() uint64 {
	if m != nil && m.Packets != nil {
		return *m.Packets
	}
	return 0
}

func (m *CounterStats) GetBytes() uint64 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

type PolicerStats struct {
	Name                 *string               `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	OutOfSpecPackets     *uint64               `protobuf:"varint,2,opt,name=out_of_spec_packets" json:"out_of_spec_packets,omitempty"`
	OutOfSpecBytes       *uint64               `protobuf:"varint,3,opt,name=out_of_spec_bytes" json:"out_of_spec_bytes,omitempty"`
	ExtendedPolicerStats *ExtendedPolicerStats `protobuf:"bytes,4,opt,name=extended_policer_stats" json:"extended_policer_stats,omitempty"`
	XXX_unrecognized     []byte                `json:"-"`
}

func (m *PolicerStats) Reset()                    { *m = PolicerStats{} }
func (m *PolicerStats) String() string            { return proto.CompactTextString(m) }
func (*PolicerStats) ProtoMessage()               {}
func (*PolicerStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PolicerStats) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PolicerStats) GetOutOfSpecPackets() uint64 {
	if m != nil && m.OutOfSpecPackets != nil {
		return *m.OutOfSpecPackets
	}
	return 0
}

func (m *PolicerStats) GetOutOfSpecBytes() uint64 {
	if m != nil && m.OutOfSpecBytes != nil {
		return *m.OutOfSpecBytes
	}
	return 0
}

func (m *PolicerStats) GetExtendedPolicerStats() *ExtendedPolicerStats {
	if m != nil {
		return m.ExtendedPolicerStats
	}
	return nil
}

type ExtendedPolicerStats struct {
	OfferedPackets     *uint64 `protobuf:"varint,1,opt,name=offered_packets" json:"offered_packets,omitempty"`
	OfferedBytes       *uint64 `protobuf:"varint,2,opt,name=offered_bytes" json:"offered_bytes,omitempty"`
	TransmittedPackets *uint64 `protobuf:"varint,3,opt,name=transmitted_packets" json:"transmitted_packets,omitempty"`
	TransmittedBytes   *uint64 `protobuf:"varint,4,opt,name=transmitted_bytes" json:"transmitted_bytes,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *ExtendedPolicerStats) Reset()                    { *m = ExtendedPolicerStats{} }
func (m *ExtendedPolicerStats) String() string            { return proto.CompactTextString(m) }
func (*ExtendedPolicerStats) ProtoMessage()               {}
func (*ExtendedPolicerStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ExtendedPolicerStats) GetOfferedPackets() uint64 {
	if m != nil && m.OfferedPackets != nil {
		return *m.OfferedPackets
	}
	return 0
}

func (m *ExtendedPolicerStats) GetOfferedBytes() uint64 {
	if m != nil && m.OfferedBytes != nil {
		return *m.OfferedBytes
	}
	return 0
}

func (m *ExtendedPolicerStats) GetTransmittedPackets() uint64 {
	if m != nil && m.TransmittedPackets != nil {
		return *m.TransmittedPackets
	}
	return 0
}

func (m *ExtendedPolicerStats) GetTransmittedBytes() uint64 {
	if m != nil && m.TransmittedBytes != nil {
		return *m.TransmittedBytes
	}
	return 0
}

type HierarchicalPolicerStats struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	PremiumPackets   *uint64 `protobuf:"varint,2,opt,name=premium_packets" json:"premium_packets,omitempty"`
	PremiumBytes     *uint64 `protobuf:"varint,3,opt,name=premium_bytes" json:"premium_bytes,omitempty"`
	AggregatePackets *uint64 `protobuf:"varint,4,opt,name=aggregate_packets" json:"aggregate_packets,omitempty"`
	AggregateBytes   *uint64 `protobuf:"varint,5,opt,name=aggregate_bytes" json:"aggregate_bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HierarchicalPolicerStats) Reset()                    { *m = HierarchicalPolicerStats{} }
func (m *HierarchicalPolicerStats) String() string            { return proto.CompactTextString(m) }
func (*HierarchicalPolicerStats) ProtoMessage()               {}
func (*HierarchicalPolicerStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *HierarchicalPolicerStats) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *HierarchicalPolicerStats) GetPremiumPackets() uint64 {
	if m != nil && m.PremiumPackets != nil {
		return *m.PremiumPackets
	}
	return 0
}

func (m *HierarchicalPolicerStats) GetPremiumBytes() uint64 {
	if m != nil && m.PremiumBytes != nil {
		return *m.PremiumBytes
	}
	return 0
}

func (m *HierarchicalPolicerStats) GetAggregatePackets() uint64 {
	if m != nil && m.AggregatePackets != nil {
		return *m.AggregatePackets
	}
	return 0
}

func (m *HierarchicalPolicerStats) GetAggregateBytes() uint64 {
	if m != nil && m.AggregateBytes != nil {
		return *m.AggregateBytes
	}
	return 0
}

var E_JnprFirewallExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*Firewall)(nil),
	Field:         6,
	Name:          "jnpr_firewall_ext",
	Tag:           "bytes,6,opt,name=jnpr_firewall_ext",
	Filename:      "firewall.proto",
}

func init() {
	proto.RegisterType((*Firewall)(nil), "Firewall")
	proto.RegisterType((*FirewallStats)(nil), "FirewallStats")
	proto.RegisterType((*MemoryUsage)(nil), "MemoryUsage")
	proto.RegisterType((*CounterStats)(nil), "CounterStats")
	proto.RegisterType((*PolicerStats)(nil), "PolicerStats")
	proto.RegisterType((*ExtendedPolicerStats)(nil), "ExtendedPolicerStats")
	proto.RegisterType((*HierarchicalPolicerStats)(nil), "HierarchicalPolicerStats")
	proto.RegisterExtension(E_JnprFirewallExt)
}

func init() { proto.RegisterFile("firewall.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xd5, 0xe6, 0x03, 0x9a, 0x49, 0xdc, 0x12, 0xa7, 0x14, 0x13, 0x55, 0x95, 0x65, 0x55, 0x28,
	0x27, 0x1f, 0x22, 0x71, 0x41, 0x54, 0x42, 0x20, 0x10, 0x42, 0x02, 0x81, 0x2a, 0xce, 0xd6, 0xe2,
	0x8c, 0x53, 0x53, 0xaf, 0x77, 0xb5, 0x3b, 0x56, 0x9b, 0x2b, 0x3f, 0x83, 0x13, 0xff, 0x80, 0x3f,
	0xc7, 0x0f, 0x40, 0xf6, 0x26, 0xe9, 0xba, 0x98, 0xeb, 0x9b, 0xf7, 0xde, 0xbc, 0x79, 0xf6, 0xc2,
	0x61, 0x96, 0x6b, 0xbc, 0xe1, 0x45, 0x11, 0x2b, 0x2d, 0x49, 0xce, 0x67, 0x84, 0x05, 0x0a, 0x24,
	0xbd, 0x49, 0x48, 0x2a, 0x0b, 0x46, 0x4b, 0x38, 0x78, 0xb7, 0xa5, 0xf9, 0xcf, 0xee, 0x24, 0x89,
	0x21, 0x4e, 0x26, 0x60, 0x61, 0x7f, 0x31, 0x5e, 0x1e, 0xc6, 0x3b, 0xca, 0x65, 0x8d, 0x46, 0x7f,
	0x18, 0x78, 0x2d, 0xc4, 0x9f, 0xc3, 0x38, 0xcb, 0x0b, 0x42, 0x9d, 0x94, 0x5c, 0x60, 0xc0, 0xc2,
	0xde, 0x62, 0xf4, 0x7a, 0xf8, 0xe3, 0x55, 0xef, 0x80, 0xf9, 0x01, 0x8c, 0x28, 0x17, 0x68, 0x88,
	0x0b, 0x15, 0xf4, 0x42, 0xb6, 0x18, 0x34, 0x93, 0x47, 0xcc, 0x8f, 0x60, 0x22, 0x50, 0x48, 0xbd,
	0x49, 0x2a, 0xc3, 0xd7, 0x18, 0xf4, 0x9b, 0x6d, 0x93, 0xf8, 0x63, 0x03, 0x7e, 0xad, 0x31, 0xff,
	0x1c, 0xbc, 0x54, 0x56, 0x65, 0x6d, 0x6d, 0x23, 0x0d, 0x1a, 0x92, 0x17, 0xbf, 0xb1, 0xa8, 0xdd,
	0x7f, 0x0e, 0x9e, 0x92, 0x45, 0x9e, 0xee, 0x59, 0xc3, 0x2d, 0xeb, 0xb3, 0x45, 0x2d, 0xeb, 0x02,
	0xe6, 0x57, 0x39, 0x6a, 0xae, 0xd3, 0xab, 0x3c, 0xe5, 0x45, 0xd2, 0x96, 0x3c, 0x68, 0x24, 0x4f,
	0xe3, 0xf7, 0x0e, 0xc5, 0x95, 0x47, 0x2f, 0x61, 0xec, 0x26, 0x9b, 0xc1, 0xa0, 0xf3, 0x58, 0x5e,
	0x14, 0x32, 0xe5, 0x84, 0x2b, 0xe7, 0xd8, 0x90, 0x45, 0x5f, 0x60, 0xd2, 0x8a, 0xdc, 0x29, 0x3f,
	0x81, 0x87, 0x8a, 0xa7, 0xd7, 0x48, 0xc6, 0x11, 0x07, 0xcc, 0x3f, 0x86, 0xe1, 0xb7, 0x0d, 0xa1,
	0x09, 0xfa, 0x0e, 0x1a, 0xfd, 0x62, 0x30, 0x69, 0x1d, 0xd8, 0xe9, 0x19, 0xc1, 0x4c, 0x56, 0x94,
	0xc8, 0x2c, 0x31, 0x0a, 0xd3, 0xa4, 0xd3, 0x3f, 0x84, 0xa9, 0xcb, 0xf9, 0x77, 0x97, 0xff, 0x1c,
	0x4e, 0xf0, 0x96, 0xb0, 0x5c, 0xe1, 0xea, 0x5e, 0x6f, 0x83, 0x90, 0x2d, 0xc6, 0xcb, 0xc7, 0xf1,
	0xdb, 0xed, 0xb8, 0xd5, 0xd9, 0x4f, 0x06, 0xc7, 0x5d, 0x03, 0xff, 0x0c, 0x8e, 0x64, 0x96, 0xa1,
	0xae, 0xed, 0xb6, 0x89, 0x98, 0xbb, 0xef, 0x14, 0xbc, 0xdd, 0xdc, 0xa6, 0x69, 0xe5, 0x8d, 0x60,
	0x46, 0x9a, 0x97, 0x46, 0xe4, 0x44, 0x8e, 0x43, 0xff, 0xde, 0x4d, 0x2e, 0xc7, 0xba, 0x0c, 0xdc,
	0xfe, 0x7e, 0x33, 0x08, 0xfe, 0xf7, 0xb5, 0xbb, 0xbb, 0x3c, 0x83, 0x23, 0xa5, 0x51, 0xe4, 0x95,
	0xe8, 0xee, 0xf1, 0x14, 0xbc, 0xdd, 0xbc, 0xa3, 0xc3, 0x10, 0xa6, 0x7c, 0xbd, 0xd6, 0xb8, 0xe6,
	0x84, 0x7b, 0xbd, 0x9b, 0xa8, 0xf6, 0xbf, 0x63, 0x58, 0x87, 0xa1, 0x33, 0x7f, 0x71, 0x01, 0xd3,
	0xef, 0xa5, 0xd2, 0xc9, 0xfe, 0x99, 0xe2, 0x2d, 0xf9, 0x4f, 0xe2, 0x0f, 0x55, 0x99, 0x2b, 0xd4,
	0x9f, 0x90, 0x6e, 0xa4, 0xbe, 0x36, 0x97, 0x58, 0x1a, 0xa9, 0xeb, 0x3f, 0xba, 0xfe, 0x32, 0xa3,
	0xfd, 0xeb, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x33, 0xfa, 0xba, 0xac, 0x12, 0x04, 0x00, 0x00,
}
