// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inline_jflow.proto

/*
Package inline_jflow is a generated protocol buffer package.

It is generated from these files:
	inline_jflow.proto

It has these top-level messages:
	InlineJflow
	InlineJflowNpuStats
*/
package inline_jflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InlineJflow struct {
	Ipv4FlowsExportFormat             *string                `protobuf:"bytes,2,opt,name=ipv4_flows_export_format" json:"ipv4_flows_export_format,omitempty"`
	Ipv6FlowsExportFormat             *string                `protobuf:"bytes,3,opt,name=ipv6_flows_export_format" json:"ipv6_flows_export_format,omitempty"`
	VplsFlowsExportFormat             *string                `protobuf:"bytes,4,opt,name=vpls_flows_export_format" json:"vpls_flows_export_format,omitempty"`
	MplsFlowsExportFormat             *string                `protobuf:"bytes,5,opt,name=mpls_flows_export_format" json:"mpls_flows_export_format,omitempty"`
	Ipv4RouteRecordCnt                *uint32                `protobuf:"varint,6,opt,name=ipv4_route_record_cnt" json:"ipv4_route_record_cnt,omitempty"`
	Ipv6RouteRecordCnt                *uint32                `protobuf:"varint,7,opt,name=ipv6_route_record_cnt" json:"ipv6_route_record_cnt,omitempty"`
	MplsRouteRecordCnt                *uint32                `protobuf:"varint,8,opt,name=mpls_route_record_cnt" json:"mpls_route_record_cnt,omitempty"`
	AutonomousSystemRecordCnt         *uint32                `protobuf:"varint,9,opt,name=autonomous_system_record_cnt" json:"autonomous_system_record_cnt,omitempty"`
	Ipv4MaxFlowsCount                 *uint64                `protobuf:"varint,10,opt,name=ipv4_max_flows_count" json:"ipv4_max_flows_count,omitempty"`
	Ipv6MaxFlowsCount                 *uint64                `protobuf:"varint,11,opt,name=ipv6_max_flows_count" json:"ipv6_max_flows_count,omitempty"`
	VplsMaxFlowsCount                 *uint64                `protobuf:"varint,12,opt,name=vpls_max_flows_count" json:"vpls_max_flows_count,omitempty"`
	MplsMaxFlowsCount                 *uint64                `protobuf:"varint,13,opt,name=mpls_max_flows_count" json:"mpls_max_flows_count,omitempty"`
	MemoryAllocFailCnt                *uint32                `protobuf:"varint,14,opt,name=memory_alloc_fail_cnt" json:"memory_alloc_fail_cnt,omitempty"`
	Ipv4ConfiguredObservationDomainId *uint32                `protobuf:"varint,15,opt,name=ipv4_configured_observation_domain_id" json:"ipv4_configured_observation_domain_id,omitempty"`
	Ipv6ConfiguredObservationDomainId *uint32                `protobuf:"varint,16,opt,name=ipv6_configured_observation_domain_id" json:"ipv6_configured_observation_domain_id,omitempty"`
	VplsConfiguredObservationDomainId *uint32                `protobuf:"varint,17,opt,name=vpls_configured_observation_domain_id" json:"vpls_configured_observation_domain_id,omitempty"`
	MplsConfiguredObservationDomainId *uint32                `protobuf:"varint,18,opt,name=mpls_configured_observation_domain_id" json:"mpls_configured_observation_domain_id,omitempty"`
	LastClearTimestamp                *uint32                `protobuf:"varint,19,opt,name=last_clear_timestamp" json:"last_clear_timestamp,omitempty"`
	Ipv6ExtendedAttribute             *bool                  `protobuf:"varint,20,opt,name=ipv6_extended_attribute" json:"ipv6_extended_attribute,omitempty"`
	FlexibleFlowSizing                *bool                  `protobuf:"varint,21,opt,name=flexible_flow_sizing" json:"flexible_flow_sizing,omitempty"`
	UseExtendedFlowMemory             *bool                  `protobuf:"varint,22,opt,name=use_extended_flow_memory" json:"use_extended_flow_memory,omitempty"`
	NpuStats                          []*InlineJflowNpuStats `protobuf:"bytes,50,rep,name=npu_stats" json:"npu_stats,omitempty"`
	XXX_unrecognized                  []byte                 `json:"-"`
}

func (m *InlineJflow) Reset()                    { *m = InlineJflow{} }
func (m *InlineJflow) String() string            { return proto.CompactTextString(m) }
func (*InlineJflow) ProtoMessage()               {}
func (*InlineJflow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InlineJflow) GetIpv4FlowsExportFormat() string {
	if m != nil && m.Ipv4FlowsExportFormat != nil {
		return *m.Ipv4FlowsExportFormat
	}
	return ""
}

func (m *InlineJflow) GetIpv6FlowsExportFormat() string {
	if m != nil && m.Ipv6FlowsExportFormat != nil {
		return *m.Ipv6FlowsExportFormat
	}
	return ""
}

func (m *InlineJflow) GetVplsFlowsExportFormat() string {
	if m != nil && m.VplsFlowsExportFormat != nil {
		return *m.VplsFlowsExportFormat
	}
	return ""
}

func (m *InlineJflow) GetMplsFlowsExportFormat() string {
	if m != nil && m.MplsFlowsExportFormat != nil {
		return *m.MplsFlowsExportFormat
	}
	return ""
}

func (m *InlineJflow) GetIpv4RouteRecordCnt() uint32 {
	if m != nil && m.Ipv4RouteRecordCnt != nil {
		return *m.Ipv4RouteRecordCnt
	}
	return 0
}

func (m *InlineJflow) GetIpv6RouteRecordCnt() uint32 {
	if m != nil && m.Ipv6RouteRecordCnt != nil {
		return *m.Ipv6RouteRecordCnt
	}
	return 0
}

func (m *InlineJflow) GetMplsRouteRecordCnt() uint32 {
	if m != nil && m.MplsRouteRecordCnt != nil {
		return *m.MplsRouteRecordCnt
	}
	return 0
}

func (m *InlineJflow) GetAutonomousSystemRecordCnt() uint32 {
	if m != nil && m.AutonomousSystemRecordCnt != nil {
		return *m.AutonomousSystemRecordCnt
	}
	return 0
}

func (m *InlineJflow) GetIpv4MaxFlowsCount() uint64 {
	if m != nil && m.Ipv4MaxFlowsCount != nil {
		return *m.Ipv4MaxFlowsCount
	}
	return 0
}

func (m *InlineJflow) GetIpv6MaxFlowsCount() uint64 {
	if m != nil && m.Ipv6MaxFlowsCount != nil {
		return *m.Ipv6MaxFlowsCount
	}
	return 0
}

func (m *InlineJflow) GetVplsMaxFlowsCount() uint64 {
	if m != nil && m.VplsMaxFlowsCount != nil {
		return *m.VplsMaxFlowsCount
	}
	return 0
}

func (m *InlineJflow) GetMplsMaxFlowsCount() uint64 {
	if m != nil && m.MplsMaxFlowsCount != nil {
		return *m.MplsMaxFlowsCount
	}
	return 0
}

func (m *InlineJflow) GetMemoryAllocFailCnt() uint32 {
	if m != nil && m.MemoryAllocFailCnt != nil {
		return *m.MemoryAllocFailCnt
	}
	return 0
}

func (m *InlineJflow) GetIpv4ConfiguredObservationDomainId() uint32 {
	if m != nil && m.Ipv4ConfiguredObservationDomainId != nil {
		return *m.Ipv4ConfiguredObservationDomainId
	}
	return 0
}

func (m *InlineJflow) GetIpv6ConfiguredObservationDomainId() uint32 {
	if m != nil && m.Ipv6ConfiguredObservationDomainId != nil {
		return *m.Ipv6ConfiguredObservationDomainId
	}
	return 0
}

func (m *InlineJflow) GetVplsConfiguredObservationDomainId() uint32 {
	if m != nil && m.VplsConfiguredObservationDomainId != nil {
		return *m.VplsConfiguredObservationDomainId
	}
	return 0
}

func (m *InlineJflow) GetMplsConfiguredObservationDomainId() uint32 {
	if m != nil && m.MplsConfiguredObservationDomainId != nil {
		return *m.MplsConfiguredObservationDomainId
	}
	return 0
}

func (m *InlineJflow) GetLastClearTimestamp() uint32 {
	if m != nil && m.LastClearTimestamp != nil {
		return *m.LastClearTimestamp
	}
	return 0
}

func (m *InlineJflow) GetIpv6ExtendedAttribute() bool {
	if m != nil && m.Ipv6ExtendedAttribute != nil {
		return *m.Ipv6ExtendedAttribute
	}
	return false
}

func (m *InlineJflow) GetFlexibleFlowSizing() bool {
	if m != nil && m.FlexibleFlowSizing != nil {
		return *m.FlexibleFlowSizing
	}
	return false
}

func (m *InlineJflow) GetUseExtendedFlowMemory() bool {
	if m != nil && m.UseExtendedFlowMemory != nil {
		return *m.UseExtendedFlowMemory
	}
	return false
}

func (m *InlineJflow) GetNpuStats() []*InlineJflowNpuStats {
	if m != nil {
		return m.NpuStats
	}
	return nil
}

type InlineJflowNpuStats struct {
	NpuIdentifier                     *uint32  `protobuf:"varint,1,req,name=npu_identifier" json:"npu_identifier,omitempty"`
	Ipv4FlowPackets                   *uint64  `protobuf:"varint,51,opt,name=ipv4_flow_packets" json:"ipv4_flow_packets,omitempty"`
	Ipv4FlowBytes                     *uint64  `protobuf:"varint,52,opt,name=ipv4_flow_bytes" json:"ipv4_flow_bytes,omitempty"`
	Ipv4TotalFlows                    *uint64  `protobuf:"varint,53,opt,name=ipv4_total_flows" json:"ipv4_total_flows,omitempty"`
	Ipv4ActiveFlows                   *uint64  `protobuf:"varint,54,opt,name=ipv4_active_flows" json:"ipv4_active_flows,omitempty"`
	Ipv4FlowsExported                 *uint64  `protobuf:"varint,55,opt,name=ipv4_flows_exported" json:"ipv4_flows_exported,omitempty"`
	Ipv4PacketsExported               *uint64  `protobuf:"varint,56,opt,name=ipv4_packets_exported" json:"ipv4_packets_exported,omitempty"`
	Ipv4FlowsInactiveTimedOut         *uint64  `protobuf:"varint,57,opt,name=ipv4_flows_inactive_timed_out" json:"ipv4_flows_inactive_timed_out,omitempty"`
	Ipv4FlowsActiveTimedOut           *uint64  `protobuf:"varint,58,opt,name=ipv4_flows_active_timed_out" json:"ipv4_flows_active_timed_out,omitempty"`
	Ipv4FlowCreateFailure             *uint64  `protobuf:"varint,59,opt,name=ipv4_flow_create_failure" json:"ipv4_flow_create_failure,omitempty"`
	Ipv4RouteLookupFailure            *uint64  `protobuf:"varint,60,opt,name=ipv4_route_lookup_failure" json:"ipv4_route_lookup_failure,omitempty"`
	Ipv4AutonomousSystemLookupFailure *uint64  `protobuf:"varint,61,opt,name=ipv4_autonomous_system_lookup_failure" json:"ipv4_autonomous_system_lookup_failure,omitempty"`
	Ipv4FlowPacketExportFailure       *uint64  `protobuf:"varint,62,opt,name=ipv4_flow_packet_export_failure" json:"ipv4_flow_packet_export_failure,omitempty"`
	Ipv4FlowTableUtilization          *float32 `protobuf:"fixed32,63,opt,name=ipv4_flow_table_utilization" json:"ipv4_flow_table_utilization,omitempty"`
	Ipv4FlowInsertCount               *uint64  `protobuf:"varint,64,opt,name=ipv4_flow_insert_count" json:"ipv4_flow_insert_count,omitempty"`
	Ipv6FlowPackets                   *uint64  `protobuf:"varint,101,opt,name=ipv6_flow_packets" json:"ipv6_flow_packets,omitempty"`
	Ipv6FlowBytes                     *uint64  `protobuf:"varint,102,opt,name=ipv6_flow_bytes" json:"ipv6_flow_bytes,omitempty"`
	Ipv6TotalFlows                    *uint64  `protobuf:"varint,103,opt,name=ipv6_total_flows" json:"ipv6_total_flows,omitempty"`
	Ipv6ActiveFlows                   *uint64  `protobuf:"varint,104,opt,name=ipv6_active_flows" json:"ipv6_active_flows,omitempty"`
	Ipv6FlowsExported                 *uint64  `protobuf:"varint,105,opt,name=ipv6_flows_exported" json:"ipv6_flows_exported,omitempty"`
	Ipv6PacketsExported               *uint64  `protobuf:"varint,106,opt,name=ipv6_packets_exported" json:"ipv6_packets_exported,omitempty"`
	Ipv6FlowsInactiveTimedOut         *uint64  `protobuf:"varint,107,opt,name=ipv6_flows_inactive_timed_out" json:"ipv6_flows_inactive_timed_out,omitempty"`
	Ipv6FlowsActiveTimedOut           *uint64  `protobuf:"varint,108,opt,name=ipv6_flows_active_timed_out" json:"ipv6_flows_active_timed_out,omitempty"`
	Ipv6FlowCreateFailure             *uint64  `protobuf:"varint,109,opt,name=ipv6_flow_create_failure" json:"ipv6_flow_create_failure,omitempty"`
	Ipv6RouteLookupFailure            *uint64  `protobuf:"varint,110,opt,name=ipv6_route_lookup_failure" json:"ipv6_route_lookup_failure,omitempty"`
	Ipv6AutonomousSystemLookupFailure *uint64  `protobuf:"varint,111,opt,name=ipv6_autonomous_system_lookup_failure" json:"ipv6_autonomous_system_lookup_failure,omitempty"`
	Ipv6FlowPacketExportFailure       *uint64  `protobuf:"varint,112,opt,name=ipv6_flow_packet_export_failure" json:"ipv6_flow_packet_export_failure,omitempty"`
	Ipv6FlowTableUtilization          *float32 `protobuf:"fixed32,113,opt,name=ipv6_flow_table_utilization" json:"ipv6_flow_table_utilization,omitempty"`
	Ipv6FlowInsertCount               *uint64  `protobuf:"varint,114,opt,name=ipv6_flow_insert_count" json:"ipv6_flow_insert_count,omitempty"`
	VplsFlowPackets                   *uint64  `protobuf:"varint,151,opt,name=vpls_flow_packets" json:"vpls_flow_packets,omitempty"`
	VplsFlowBytes                     *uint64  `protobuf:"varint,152,opt,name=vpls_flow_bytes" json:"vpls_flow_bytes,omitempty"`
	VplsTotalFlows                    *uint64  `protobuf:"varint,153,opt,name=vpls_total_flows" json:"vpls_total_flows,omitempty"`
	VplsActiveFlows                   *uint64  `protobuf:"varint,154,opt,name=vpls_active_flows" json:"vpls_active_flows,omitempty"`
	VplsFlowsExported                 *uint64  `protobuf:"varint,155,opt,name=vpls_flows_exported" json:"vpls_flows_exported,omitempty"`
	VplsPacketsExported               *uint64  `protobuf:"varint,156,opt,name=vpls_packets_exported" json:"vpls_packets_exported,omitempty"`
	VplsFlowsInactiveTimedOut         *uint64  `protobuf:"varint,157,opt,name=vpls_flows_inactive_timed_out" json:"vpls_flows_inactive_timed_out,omitempty"`
	VplsFlowsActiveTimedOut           *uint64  `protobuf:"varint,158,opt,name=vpls_flows_active_timed_out" json:"vpls_flows_active_timed_out,omitempty"`
	VplsFlowCreateFailure             *uint64  `protobuf:"varint,159,opt,name=vpls_flow_create_failure" json:"vpls_flow_create_failure,omitempty"`
	VplsRouteLookupFailure            *uint64  `protobuf:"varint,160,opt,name=vpls_route_lookup_failure" json:"vpls_route_lookup_failure,omitempty"`
	VplsAutonomousSystemLookupFailure *uint64  `protobuf:"varint,161,opt,name=vpls_autonomous_system_lookup_failure" json:"vpls_autonomous_system_lookup_failure,omitempty"`
	VplsFlowPacketExportFailure       *uint64  `protobuf:"varint,162,opt,name=vpls_flow_packet_export_failure" json:"vpls_flow_packet_export_failure,omitempty"`
	VplsFlowTableUtilization          *float32 `protobuf:"fixed32,163,opt,name=vpls_flow_table_utilization" json:"vpls_flow_table_utilization,omitempty"`
	VplsFlowInsertCount               *uint64  `protobuf:"varint,164,opt,name=vpls_flow_insert_count" json:"vpls_flow_insert_count,omitempty"`
	MplsFlowPackets                   *uint64  `protobuf:"varint,201,opt,name=mpls_flow_packets" json:"mpls_flow_packets,omitempty"`
	MplsFlowBytes                     *uint64  `protobuf:"varint,202,opt,name=mpls_flow_bytes" json:"mpls_flow_bytes,omitempty"`
	MplsTotalFlows                    *uint64  `protobuf:"varint,203,opt,name=mpls_total_flows" json:"mpls_total_flows,omitempty"`
	MplsActiveFlows                   *uint64  `protobuf:"varint,204,opt,name=mpls_active_flows" json:"mpls_active_flows,omitempty"`
	MplsFlowsExported                 *uint64  `protobuf:"varint,205,opt,name=mpls_flows_exported" json:"mpls_flows_exported,omitempty"`
	MplsPacketsExported               *uint64  `protobuf:"varint,206,opt,name=mpls_packets_exported" json:"mpls_packets_exported,omitempty"`
	MplsFlowsInactiveTimedOut         *uint64  `protobuf:"varint,207,opt,name=mpls_flows_inactive_timed_out" json:"mpls_flows_inactive_timed_out,omitempty"`
	MplsFlowsActiveTimedOut           *uint64  `protobuf:"varint,208,opt,name=mpls_flows_active_timed_out" json:"mpls_flows_active_timed_out,omitempty"`
	MplsFlowCreateFailure             *uint64  `protobuf:"varint,209,opt,name=mpls_flow_create_failure" json:"mpls_flow_create_failure,omitempty"`
	MplsRouteLookupFailure            *uint64  `protobuf:"varint,210,opt,name=mpls_route_lookup_failure" json:"mpls_route_lookup_failure,omitempty"`
	MplsAutonomousSystemLookupFailure *uint64  `protobuf:"varint,211,opt,name=mpls_autonomous_system_lookup_failure" json:"mpls_autonomous_system_lookup_failure,omitempty"`
	MplsFlowPacketExportFailure       *uint64  `protobuf:"varint,212,opt,name=mpls_flow_packet_export_failure" json:"mpls_flow_packet_export_failure,omitempty"`
	MplsFlowTableUtilization          *float32 `protobuf:"fixed32,213,opt,name=mpls_flow_table_utilization" json:"mpls_flow_table_utilization,omitempty"`
	MplsFlowInsertCount               *uint64  `protobuf:"varint,214,opt,name=mpls_flow_insert_count" json:"mpls_flow_insert_count,omitempty"`
	XXX_unrecognized                  []byte   `json:"-"`
}

func (m *InlineJflowNpuStats) Reset()                    { *m = InlineJflowNpuStats{} }
func (m *InlineJflowNpuStats) String() string            { return proto.CompactTextString(m) }
func (*InlineJflowNpuStats) ProtoMessage()               {}
func (*InlineJflowNpuStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InlineJflowNpuStats) GetNpuIdentifier() uint32 {
	if m != nil && m.NpuIdentifier != nil {
		return *m.NpuIdentifier
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4FlowPackets() uint64 {
	if m != nil && m.Ipv4FlowPackets != nil {
		return *m.Ipv4FlowPackets
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4FlowBytes() uint64 {
	if m != nil && m.Ipv4FlowBytes != nil {
		return *m.Ipv4FlowBytes
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4TotalFlows() uint64 {
	if m != nil && m.Ipv4TotalFlows != nil {
		return *m.Ipv4TotalFlows
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4ActiveFlows() uint64 {
	if m != nil && m.Ipv4ActiveFlows != nil {
		return *m.Ipv4ActiveFlows
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4FlowsExported() uint64 {
	if m != nil && m.Ipv4FlowsExported != nil {
		return *m.Ipv4FlowsExported
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4PacketsExported() uint64 {
	if m != nil && m.Ipv4PacketsExported != nil {
		return *m.Ipv4PacketsExported
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4FlowsInactiveTimedOut() uint64 {
	if m != nil && m.Ipv4FlowsInactiveTimedOut != nil {
		return *m.Ipv4FlowsInactiveTimedOut
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4FlowsActiveTimedOut() uint64 {
	if m != nil && m.Ipv4FlowsActiveTimedOut != nil {
		return *m.Ipv4FlowsActiveTimedOut
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4FlowCreateFailure() uint64 {
	if m != nil && m.Ipv4FlowCreateFailure != nil {
		return *m.Ipv4FlowCreateFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4RouteLookupFailure() uint64 {
	if m != nil && m.Ipv4RouteLookupFailure != nil {
		return *m.Ipv4RouteLookupFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4AutonomousSystemLookupFailure() uint64 {
	if m != nil && m.Ipv4AutonomousSystemLookupFailure != nil {
		return *m.Ipv4AutonomousSystemLookupFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4FlowPacketExportFailure() uint64 {
	if m != nil && m.Ipv4FlowPacketExportFailure != nil {
		return *m.Ipv4FlowPacketExportFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4FlowTableUtilization() float32 {
	if m != nil && m.Ipv4FlowTableUtilization != nil {
		return *m.Ipv4FlowTableUtilization
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv4FlowInsertCount() uint64 {
	if m != nil && m.Ipv4FlowInsertCount != nil {
		return *m.Ipv4FlowInsertCount
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6FlowPackets() uint64 {
	if m != nil && m.Ipv6FlowPackets != nil {
		return *m.Ipv6FlowPackets
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6FlowBytes() uint64 {
	if m != nil && m.Ipv6FlowBytes != nil {
		return *m.Ipv6FlowBytes
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6TotalFlows() uint64 {
	if m != nil && m.Ipv6TotalFlows != nil {
		return *m.Ipv6TotalFlows
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6ActiveFlows() uint64 {
	if m != nil && m.Ipv6ActiveFlows != nil {
		return *m.Ipv6ActiveFlows
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6FlowsExported() uint64 {
	if m != nil && m.Ipv6FlowsExported != nil {
		return *m.Ipv6FlowsExported
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6PacketsExported() uint64 {
	if m != nil && m.Ipv6PacketsExported != nil {
		return *m.Ipv6PacketsExported
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6FlowsInactiveTimedOut() uint64 {
	if m != nil && m.Ipv6FlowsInactiveTimedOut != nil {
		return *m.Ipv6FlowsInactiveTimedOut
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6FlowsActiveTimedOut() uint64 {
	if m != nil && m.Ipv6FlowsActiveTimedOut != nil {
		return *m.Ipv6FlowsActiveTimedOut
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6FlowCreateFailure() uint64 {
	if m != nil && m.Ipv6FlowCreateFailure != nil {
		return *m.Ipv6FlowCreateFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6RouteLookupFailure() uint64 {
	if m != nil && m.Ipv6RouteLookupFailure != nil {
		return *m.Ipv6RouteLookupFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6AutonomousSystemLookupFailure() uint64 {
	if m != nil && m.Ipv6AutonomousSystemLookupFailure != nil {
		return *m.Ipv6AutonomousSystemLookupFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6FlowPacketExportFailure() uint64 {
	if m != nil && m.Ipv6FlowPacketExportFailure != nil {
		return *m.Ipv6FlowPacketExportFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6FlowTableUtilization() float32 {
	if m != nil && m.Ipv6FlowTableUtilization != nil {
		return *m.Ipv6FlowTableUtilization
	}
	return 0
}

func (m *InlineJflowNpuStats) GetIpv6FlowInsertCount() uint64 {
	if m != nil && m.Ipv6FlowInsertCount != nil {
		return *m.Ipv6FlowInsertCount
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsFlowPackets() uint64 {
	if m != nil && m.VplsFlowPackets != nil {
		return *m.VplsFlowPackets
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsFlowBytes() uint64 {
	if m != nil && m.VplsFlowBytes != nil {
		return *m.VplsFlowBytes
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsTotalFlows() uint64 {
	if m != nil && m.VplsTotalFlows != nil {
		return *m.VplsTotalFlows
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsActiveFlows() uint64 {
	if m != nil && m.VplsActiveFlows != nil {
		return *m.VplsActiveFlows
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsFlowsExported() uint64 {
	if m != nil && m.VplsFlowsExported != nil {
		return *m.VplsFlowsExported
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsPacketsExported() uint64 {
	if m != nil && m.VplsPacketsExported != nil {
		return *m.VplsPacketsExported
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsFlowsInactiveTimedOut() uint64 {
	if m != nil && m.VplsFlowsInactiveTimedOut != nil {
		return *m.VplsFlowsInactiveTimedOut
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsFlowsActiveTimedOut() uint64 {
	if m != nil && m.VplsFlowsActiveTimedOut != nil {
		return *m.VplsFlowsActiveTimedOut
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsFlowCreateFailure() uint64 {
	if m != nil && m.VplsFlowCreateFailure != nil {
		return *m.VplsFlowCreateFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsRouteLookupFailure() uint64 {
	if m != nil && m.VplsRouteLookupFailure != nil {
		return *m.VplsRouteLookupFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsAutonomousSystemLookupFailure() uint64 {
	if m != nil && m.VplsAutonomousSystemLookupFailure != nil {
		return *m.VplsAutonomousSystemLookupFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsFlowPacketExportFailure() uint64 {
	if m != nil && m.VplsFlowPacketExportFailure != nil {
		return *m.VplsFlowPacketExportFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsFlowTableUtilization() float32 {
	if m != nil && m.VplsFlowTableUtilization != nil {
		return *m.VplsFlowTableUtilization
	}
	return 0
}

func (m *InlineJflowNpuStats) GetVplsFlowInsertCount() uint64 {
	if m != nil && m.VplsFlowInsertCount != nil {
		return *m.VplsFlowInsertCount
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsFlowPackets() uint64 {
	if m != nil && m.MplsFlowPackets != nil {
		return *m.MplsFlowPackets
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsFlowBytes() uint64 {
	if m != nil && m.MplsFlowBytes != nil {
		return *m.MplsFlowBytes
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsTotalFlows() uint64 {
	if m != nil && m.MplsTotalFlows != nil {
		return *m.MplsTotalFlows
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsActiveFlows() uint64 {
	if m != nil && m.MplsActiveFlows != nil {
		return *m.MplsActiveFlows
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsFlowsExported() uint64 {
	if m != nil && m.MplsFlowsExported != nil {
		return *m.MplsFlowsExported
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsPacketsExported() uint64 {
	if m != nil && m.MplsPacketsExported != nil {
		return *m.MplsPacketsExported
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsFlowsInactiveTimedOut() uint64 {
	if m != nil && m.MplsFlowsInactiveTimedOut != nil {
		return *m.MplsFlowsInactiveTimedOut
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsFlowsActiveTimedOut() uint64 {
	if m != nil && m.MplsFlowsActiveTimedOut != nil {
		return *m.MplsFlowsActiveTimedOut
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsFlowCreateFailure() uint64 {
	if m != nil && m.MplsFlowCreateFailure != nil {
		return *m.MplsFlowCreateFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsRouteLookupFailure() uint64 {
	if m != nil && m.MplsRouteLookupFailure != nil {
		return *m.MplsRouteLookupFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsAutonomousSystemLookupFailure() uint64 {
	if m != nil && m.MplsAutonomousSystemLookupFailure != nil {
		return *m.MplsAutonomousSystemLookupFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsFlowPacketExportFailure() uint64 {
	if m != nil && m.MplsFlowPacketExportFailure != nil {
		return *m.MplsFlowPacketExportFailure
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsFlowTableUtilization() float32 {
	if m != nil && m.MplsFlowTableUtilization != nil {
		return *m.MplsFlowTableUtilization
	}
	return 0
}

func (m *InlineJflowNpuStats) GetMplsFlowInsertCount() uint64 {
	if m != nil && m.MplsFlowInsertCount != nil {
		return *m.MplsFlowInsertCount
	}
	return 0
}

var E_InlineJflowStatsExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*InlineJflow)(nil),
	Field:         9,
	Name:          "inline_jflow_stats_ext",
	Tag:           "bytes,9,opt,name=inline_jflow_stats_ext",
	Filename:      "inline_jflow.proto",
}

func init() {
	proto.RegisterType((*InlineJflow)(nil), "InlineJflow")
	proto.RegisterType((*InlineJflowNpuStats)(nil), "InlineJflowNpuStats")
	proto.RegisterExtension(E_InlineJflowStatsExt)
}

func init() { proto.RegisterFile("inline_jflow.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 976 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x97, 0xdb, 0x72, 0xdc, 0x34,
	0x18, 0xc7, 0xc7, 0xe9, 0x81, 0x46, 0x69, 0x9a, 0xc4, 0x9b, 0x6c, 0x55, 0xda, 0x10, 0x13, 0x12,
	0xba, 0x1c, 0x1a, 0x66, 0x42, 0x6a, 0xa0, 0x9c, 0x3a, 0xcc, 0x70, 0x41, 0x2f, 0x7a, 0xd3, 0x07,
	0xd0, 0x38, 0xf6, 0xb7, 0x41, 0x8d, 0x65, 0x19, 0x49, 0xde, 0x66, 0x7b, 0xc9, 0x4b, 0x00, 0x85,
	0x72, 0x7e, 0x19, 0xce, 0x67, 0x9e, 0xa7, 0x63, 0xad, 0xbd, 0x2b, 0x4b, 0x76, 0xb6, 0x97, 0xeb,
	0xff, 0x4f, 0xd2, 0x27, 0xe9, 0x27, 0x5b, 0x8b, 0x7c, 0x9a, 0xa5, 0x34, 0x03, 0x72, 0x7f, 0x98,
	0xf2, 0x07, 0x7b, 0xb9, 0xe0, 0x8a, 0x3f, 0xdb, 0x53, 0x90, 0x02, 0x03, 0x25, 0xc6, 0x44, 0xf1,
	0x7c, 0xf2, 0x70, 0xfb, 0xd1, 0x79, 0xb4, 0xf4, 0x91, 0x66, 0xef, 0x94, 0xa8, 0x1f, 0x20, 0x4c,
	0xf3, 0xd1, 0x01, 0x29, 0x7f, 0x48, 0x02, 0x27, 0x39, 0x17, 0x8a, 0x0c, 0xb9, 0x60, 0x91, 0xc2,
	0x0b, 0x81, 0x37, 0x58, 0xac, 0x88, 0xb0, 0x95, 0x38, 0x53, 0x13, 0xa3, 0x3c, 0x95, 0xad, 0xc4,
	0xd9, 0x9a, 0x60, 0x5d, 0xc4, 0x39, 0x4d, 0x6c, 0xa2, 0x0d, 0x5d, 0x87, 0xe0, 0x85, 0x02, 0x22,
	0x20, 0xe6, 0x22, 0x21, 0x71, 0xa6, 0xf0, 0xf9, 0xc0, 0x1b, 0x2c, 0x57, 0x71, 0xe8, 0xc6, 0xcf,
	0xd4, 0xb1, 0xee, 0xdf, 0x89, 0x2f, 0xe8, 0x78, 0x07, 0x5d, 0x8b, 0x0a, 0xc5, 0x33, 0xce, 0x78,
	0x21, 0x89, 0x1c, 0x4b, 0x05, 0xcc, 0xa4, 0x16, 0x35, 0x75, 0x0d, 0xad, 0xeb, 0x12, 0x58, 0x74,
	0x52, 0x15, 0x1a, 0xf3, 0x22, 0x53, 0x18, 0x05, 0xde, 0xe0, 0x6c, 0x95, 0x86, 0x4e, 0xba, 0x54,
	0xa7, 0x7a, 0x09, 0xec, 0xf4, 0x62, 0x9d, 0xb2, 0xb6, 0x74, 0x59, 0xa7, 0x3b, 0x68, 0x83, 0x01,
	0xe3, 0x62, 0x4c, 0xa2, 0x34, 0xe5, 0x31, 0x19, 0x46, 0x34, 0xd5, 0x65, 0x5d, 0x2a, 0xcb, 0xfa,
	0xe0, 0xdc, 0xa7, 0xb7, 0x17, 0xb0, 0xe7, 0xdf, 0x40, 0xbb, 0xba, 0xba, 0x98, 0x67, 0x43, 0x7a,
	0x54, 0x08, 0x48, 0x08, 0x3f, 0x94, 0x20, 0x46, 0x91, 0xa2, 0x3c, 0x23, 0x09, 0x67, 0x11, 0xcd,
	0x08, 0x4d, 0xf0, 0x8a, 0x9e, 0xcc, 0x04, 0x0f, 0xe7, 0xe3, 0xab, 0x35, 0xae, 0xeb, 0x9f, 0x8b,
	0xaf, 0xd5, 0x38, 0x7b, 0x2a, 0xdc, 0xaf, 0x57, 0x36, 0x8d, 0xa4, 0x22, 0x71, 0x0a, 0x91, 0x20,
	0x8a, 0x32, 0x90, 0x2a, 0x62, 0x39, 0xee, 0xe9, 0x74, 0x0b, 0x5d, 0xd6, 0xa5, 0xc2, 0x89, 0x82,
	0x2c, 0x81, 0x84, 0x44, 0x4a, 0x09, 0x7a, 0x58, 0x28, 0xc0, 0xeb, 0x81, 0x37, 0xb8, 0x50, 0x36,
	0x1f, 0xa6, 0x70, 0x42, 0x0f, 0x53, 0xd0, 0xcb, 0x47, 0x24, 0x7d, 0x48, 0xb3, 0x23, 0xbc, 0xa1,
	0xd3, 0x00, 0xe1, 0x42, 0xc2, 0xac, 0xb5, 0x26, 0x26, 0x0b, 0x8a, 0xfb, 0x9a, 0xb8, 0x8e, 0x16,
	0xb3, 0xbc, 0x20, 0x52, 0x45, 0x4a, 0xe2, 0xfd, 0xe0, 0xcc, 0x60, 0x69, 0x7f, 0x7d, 0xcf, 0x38,
	0x04, 0x77, 0xf3, 0xe2, 0x5e, 0x99, 0x6d, 0x3f, 0xf6, 0x51, 0xaf, 0xe5, 0xb9, 0xdf, 0x47, 0x97,
	0xca, 0x0e, 0x68, 0x02, 0x99, 0xa2, 0x43, 0x0a, 0x02, 0x7b, 0xc1, 0xc2, 0x60, 0xd9, 0x0f, 0xd0,
	0xda, 0xf4, 0xf0, 0x90, 0x3c, 0x8a, 0x8f, 0x41, 0x49, 0xfc, 0x7a, 0xb9, 0xa9, 0xf5, 0xae, 0x3d,
	0x87, 0x56, 0x66, 0xc4, 0xe1, 0x58, 0x81, 0xc4, 0x07, 0x66, 0xbe, 0x85, 0x56, 0x75, 0xae, 0xb8,
	0x8a, 0xd2, 0x89, 0x1b, 0xf8, 0xa6, 0x09, 0xd4, 0x43, 0x44, 0xb1, 0xa2, 0x23, 0xa8, 0x88, 0xd0,
	0x24, 0xb6, 0x51, 0xcf, 0x39, 0xc1, 0x90, 0xe0, 0x37, 0x4c, 0x66, 0xa7, 0x3a, 0x5d, 0x55, 0x8d,
	0x33, 0xea, 0x4d, 0x93, 0x7a, 0x15, 0x6d, 0x1a, 0x3d, 0xd1, 0xac, 0x1a, 0xb3, 0xdc, 0xaf, 0x84,
	0xf0, 0x42, 0xe1, 0xb7, 0x4c, 0xfa, 0x65, 0x74, 0xd5, 0xa0, 0x1d, 0xf6, 0x96, 0xc9, 0x5e, 0x37,
	0xde, 0x32, 0x24, 0x16, 0x10, 0x29, 0xd0, 0x9a, 0x17, 0x02, 0xf0, 0xdb, 0x26, 0x38, 0x40, 0x57,
	0x8c, 0xd7, 0x40, 0xca, 0xf9, 0x71, 0x91, 0x4f, 0xc9, 0x77, 0x4c, 0xf2, 0xa0, 0x3a, 0x0f, 0xee,
	0xc1, 0xb6, 0x5a, 0xbd, 0x6b, 0xb6, 0xda, 0x43, 0x5b, 0xf6, 0x8e, 0x4d, 0x5f, 0x47, 0x15, 0xff,
	0x5e, 0xd7, 0x24, 0x89, 0x8a, 0x4a, 0x03, 0x0b, 0x45, 0x53, 0xfa, 0x50, 0x8b, 0x8e, 0xdf, 0x0f,
	0xbc, 0xc1, 0x82, 0x66, 0x03, 0xcf, 0xdf, 0x45, 0xfd, 0x19, 0x4b, 0x33, 0x09, 0x42, 0x55, 0xe7,
	0xfc, 0xb6, 0xbb, 0xa3, 0x61, 0x53, 0x1a, 0x70, 0xa5, 0x09, 0x4d, 0x69, 0x86, 0xae, 0x34, 0x61,
	0x43, 0x9a, 0xa3, 0xb6, 0x21, 0x1a, 0xd2, 0x7c, 0xec, 0x4a, 0x13, 0xda, 0xd2, 0x50, 0x57, 0x9a,
	0xd0, 0x95, 0xe6, 0xbe, 0x2b, 0x4d, 0xd8, 0x2d, 0xcd, 0xb1, 0xbb, 0x9e, 0x61, 0x97, 0x34, 0xa9,
	0x2b, 0x4d, 0xd8, 0x2a, 0x0d, 0x73, 0xa5, 0x09, 0xdb, 0xa5, 0xc9, 0x5c, 0x69, 0xc2, 0xf9, 0xd2,
	0x70, 0x57, 0x9a, 0xf0, 0x34, 0x69, 0xf2, 0xae, 0x49, 0xb6, 0x48, 0xf3, 0x89, 0x2b, 0x4d, 0xd8,
	0x22, 0x8d, 0x30, 0xbb, 0x7c, 0x1e, 0xad, 0x4d, 0x3f, 0xb1, 0x53, 0x69, 0x3e, 0xf3, 0x9a, 0x56,
	0xac, 0xcc, 0x90, 0x89, 0x35, 0x9f, 0x7b, 0x4d, 0x2b, 0x56, 0x35, 0x60, 0x6a, 0xf3, 0x85, 0xd7,
	0x36, 0x4a, 0xc3, 0x9b, 0x47, 0x0d, 0xe4, 0x05, 0xd4, 0x73, 0xbe, 0xf5, 0x90, 0xe0, 0x2f, 0x1b,
	0xd0, 0x2e, 0xda, 0xd0, 0x90, 0x63, 0xce, 0x57, 0x0d, 0xec, 0x06, 0xda, 0x34, 0xfa, 0x6a, 0x51,
	0xe7, 0x71, 0x03, 0x7f, 0x05, 0x5d, 0x35, 0x70, 0x07, 0xfe, 0xda, 0x6b, 0x3a, 0x31, 0xbb, 0x93,
	0xd8, 0xf2, 0x7c, 0xd3, 0x20, 0x5f, 0x42, 0x57, 0x46, 0xb3, 0xbb, 0x83, 0xe5, 0xc1, 0xb7, 0x0d,
	0xf4, 0x66, 0xf5, 0x95, 0x9c, 0xab, 0xcf, 0x77, 0x8d, 0x66, 0xaf, 0xa1, 0x2d, 0x7b, 0xf3, 0x6c,
	0x7f, 0xbe, 0xef, 0x9c, 0x69, 0x8b, 0x40, 0x3f, 0x78, 0xa6, 0x41, 0x2f, 0xa2, 0xfe, 0x0c, 0x6e,
	0x18, 0xf4, 0xa3, 0xbd, 0xb9, 0xcc, 0x51, 0xe8, 0x27, 0x5b, 0x21, 0x66, 0x29, 0xf4, 0xb3, 0xad,
	0x10, 0xb3, 0x15, 0xfa, 0xa5, 0x75, 0x94, 0x86, 0x42, 0xbf, 0xda, 0x0a, 0xb1, 0x16, 0x85, 0x7e,
	0xb3, 0x15, 0x62, 0xad, 0x0a, 0xfd, 0x6e, 0x2b, 0xc4, 0x4e, 0x55, 0xe8, 0x0f, 0x7b, 0x61, 0xd9,
	0x29, 0x0a, 0xfd, 0x69, 0x2b, 0xc4, 0xba, 0x14, 0xfa, 0xcb, 0x56, 0x88, 0x75, 0x2a, 0xf4, 0xb7,
	0xad, 0x10, 0x7b, 0x2a, 0x85, 0xfe, 0xb1, 0x15, 0x62, 0x73, 0x14, 0xfa, 0xb7, 0x73, 0xa6, 0x2d,
	0x0a, 0xfd, 0x67, 0x2b, 0xc4, 0xda, 0x15, 0xfa, 0xdf, 0xec, 0xf4, 0xd6, 0x87, 0xa8, 0x6f, 0xfe,
	0xcf, 0x98, 0xdc, 0xa8, 0xca, 0x9b, 0x97, 0x7f, 0x79, 0xef, 0x4e, 0x91, 0xd1, 0x1c, 0xc4, 0x5d,
	0x50, 0x0f, 0xb8, 0x38, 0x96, 0xf7, 0x20, 0x93, 0x5c, 0x48, 0x7d, 0xb5, 0x5e, 0xda, 0xbf, 0x68,
	0x5e, 0xb7, 0x9e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x64, 0xc1, 0xb4, 0x36, 0xad, 0x0c, 0x00, 0x00,
}
