// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logical_port.proto

/*
Package logical_port is a generated protocol buffer package.

It is generated from these files:
	logical_port.proto

It has these top-level messages:
	LogicalPort
	LogicalInterfaceInfo
	IngressInterfaceStats
	EgressInterfaceStats
	OperationalState
	ForwardingClassAccounting
	LogicalInterfaceQueueStats
*/
package logical_port

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogicalPort struct {
	InterfaceInfo    []*LogicalInterfaceInfo `protobuf:"bytes,1,rep,name=interface_info" json:"interface_info,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *LogicalPort) Reset()                    { *m = LogicalPort{} }
func (m *LogicalPort) String() string            { return proto.CompactTextString(m) }
func (*LogicalPort) ProtoMessage()               {}
func (*LogicalPort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogicalPort) GetInterfaceInfo() []*LogicalInterfaceInfo {
	if m != nil {
		return m.InterfaceInfo
	}
	return nil
}

type LogicalInterfaceInfo struct {
	IfName                *string                       `protobuf:"bytes,1,req,name=if_name" json:"if_name,omitempty"`
	InitTime              *uint64                       `protobuf:"varint,2,req,name=init_time" json:"init_time,omitempty"`
	SnmpIfIndex           *uint32                       `protobuf:"varint,3,opt,name=snmp_if_index" json:"snmp_if_index,omitempty"`
	ParentAeName          *string                       `protobuf:"bytes,4,opt,name=parent_ae_name" json:"parent_ae_name,omitempty"`
	IngressStats          *IngressInterfaceStats        `protobuf:"bytes,5,opt,name=ingress_stats" json:"ingress_stats,omitempty"`
	EgressStats           *EgressInterfaceStats         `protobuf:"bytes,6,opt,name=egress_stats" json:"egress_stats,omitempty"`
	OpState               *OperationalState             `protobuf:"bytes,7,opt,name=op_state" json:"op_state,omitempty"`
	AdministractiveStatus *string                       `protobuf:"bytes,8,opt,name=administractive_status" json:"administractive_status,omitempty"`
	Description           *string                       `protobuf:"bytes,9,opt,name=description" json:"description,omitempty"`
	LastChange            *uint32                       `protobuf:"varint,10,opt,name=last_change" json:"last_change,omitempty"`
	HighSpeed             *uint32                       `protobuf:"varint,11,opt,name=high_speed" json:"high_speed,omitempty"`
	IngressQueueInfo      []*LogicalInterfaceQueueStats `protobuf:"bytes,12,rep,name=ingress_queue_info" json:"ingress_queue_info,omitempty"`
	EgressQueueInfo       []*LogicalInterfaceQueueStats `protobuf:"bytes,13,rep,name=egress_queue_info" json:"egress_queue_info,omitempty"`
	XXX_unrecognized      []byte                        `json:"-"`
}

func (m *LogicalInterfaceInfo) Reset()                    { *m = LogicalInterfaceInfo{} }
func (m *LogicalInterfaceInfo) String() string            { return proto.CompactTextString(m) }
func (*LogicalInterfaceInfo) ProtoMessage()               {}
func (*LogicalInterfaceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogicalInterfaceInfo) GetIfName() string {
	if m != nil && m.IfName != nil {
		return *m.IfName
	}
	return ""
}

func (m *LogicalInterfaceInfo) GetInitTime() uint64 {
	if m != nil && m.InitTime != nil {
		return *m.InitTime
	}
	return 0
}

func (m *LogicalInterfaceInfo) GetSnmpIfIndex() uint32 {
	if m != nil && m.SnmpIfIndex != nil {
		return *m.SnmpIfIndex
	}
	return 0
}

func (m *LogicalInterfaceInfo) GetParentAeName() string {
	if m != nil && m.ParentAeName != nil {
		return *m.ParentAeName
	}
	return ""
}

func (m *LogicalInterfaceInfo) GetIngressStats() *IngressInterfaceStats {
	if m != nil {
		return m.IngressStats
	}
	return nil
}

func (m *LogicalInterfaceInfo) GetEgressStats() *EgressInterfaceStats {
	if m != nil {
		return m.EgressStats
	}
	return nil
}

func (m *LogicalInterfaceInfo) GetOpState() *OperationalState {
	if m != nil {
		return m.OpState
	}
	return nil
}

func (m *LogicalInterfaceInfo) GetAdministractiveStatus() string {
	if m != nil && m.AdministractiveStatus != nil {
		return *m.AdministractiveStatus
	}
	return ""
}

func (m *LogicalInterfaceInfo) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *LogicalInterfaceInfo) GetLastChange() uint32 {
	if m != nil && m.LastChange != nil {
		return *m.LastChange
	}
	return 0
}

func (m *LogicalInterfaceInfo) GetHighSpeed() uint32 {
	if m != nil && m.HighSpeed != nil {
		return *m.HighSpeed
	}
	return 0
}

func (m *LogicalInterfaceInfo) GetIngressQueueInfo() []*LogicalInterfaceQueueStats {
	if m != nil {
		return m.IngressQueueInfo
	}
	return nil
}

func (m *LogicalInterfaceInfo) GetEgressQueueInfo() []*LogicalInterfaceQueueStats {
	if m != nil {
		return m.EgressQueueInfo
	}
	return nil
}

type IngressInterfaceStats struct {
	IfPackets        *uint64                      `protobuf:"varint,1,req,name=if_packets" json:"if_packets,omitempty"`
	IfOctets         *uint64                      `protobuf:"varint,2,req,name=if_octets" json:"if_octets,omitempty"`
	IfUcastPackets   *uint64                      `protobuf:"varint,3,opt,name=if_ucast_packets" json:"if_ucast_packets,omitempty"`
	IfMcastPackets   *uint64                      `protobuf:"varint,4,opt,name=if_mcast_packets" json:"if_mcast_packets,omitempty"`
	IfFcStats        []*ForwardingClassAccounting `protobuf:"bytes,5,rep,name=if_fc_stats" json:"if_fc_stats,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *IngressInterfaceStats) Reset()                    { *m = IngressInterfaceStats{} }
func (m *IngressInterfaceStats) String() string            { return proto.CompactTextString(m) }
func (*IngressInterfaceStats) ProtoMessage()               {}
func (*IngressInterfaceStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IngressInterfaceStats) GetIfPackets() uint64 {
	if m != nil && m.IfPackets != nil {
		return *m.IfPackets
	}
	return 0
}

func (m *IngressInterfaceStats) GetIfOctets() uint64 {
	if m != nil && m.IfOctets != nil {
		return *m.IfOctets
	}
	return 0
}

func (m *IngressInterfaceStats) GetIfUcastPackets() uint64 {
	if m != nil && m.IfUcastPackets != nil {
		return *m.IfUcastPackets
	}
	return 0
}

func (m *IngressInterfaceStats) GetIfMcastPackets() uint64 {
	if m != nil && m.IfMcastPackets != nil {
		return *m.IfMcastPackets
	}
	return 0
}

func (m *IngressInterfaceStats) GetIfFcStats() []*ForwardingClassAccounting {
	if m != nil {
		return m.IfFcStats
	}
	return nil
}

type EgressInterfaceStats struct {
	IfPackets        *uint64 `protobuf:"varint,1,req,name=if_packets" json:"if_packets,omitempty"`
	IfOctets         *uint64 `protobuf:"varint,2,req,name=if_octets" json:"if_octets,omitempty"`
	IfUcastPackets   *uint64 `protobuf:"varint,3,opt,name=if_ucast_packets" json:"if_ucast_packets,omitempty"`
	IfMcastPackets   *uint64 `protobuf:"varint,4,opt,name=if_mcast_packets" json:"if_mcast_packets,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EgressInterfaceStats) Reset()                    { *m = EgressInterfaceStats{} }
func (m *EgressInterfaceStats) String() string            { return proto.CompactTextString(m) }
func (*EgressInterfaceStats) ProtoMessage()               {}
func (*EgressInterfaceStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EgressInterfaceStats) GetIfPackets() uint64 {
	if m != nil && m.IfPackets != nil {
		return *m.IfPackets
	}
	return 0
}

func (m *EgressInterfaceStats) GetIfOctets() uint64 {
	if m != nil && m.IfOctets != nil {
		return *m.IfOctets
	}
	return 0
}

func (m *EgressInterfaceStats) GetIfUcastPackets() uint64 {
	if m != nil && m.IfUcastPackets != nil {
		return *m.IfUcastPackets
	}
	return 0
}

func (m *EgressInterfaceStats) GetIfMcastPackets() uint64 {
	if m != nil && m.IfMcastPackets != nil {
		return *m.IfMcastPackets
	}
	return 0
}

type OperationalState struct {
	OperationalStatus *string `protobuf:"bytes,1,opt,name=operational_status" json:"operational_status,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *OperationalState) Reset()                    { *m = OperationalState{} }
func (m *OperationalState) String() string            { return proto.CompactTextString(m) }
func (*OperationalState) ProtoMessage()               {}
func (*OperationalState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *OperationalState) GetOperationalStatus() string {
	if m != nil && m.OperationalStatus != nil {
		return *m.OperationalStatus
	}
	return ""
}

type ForwardingClassAccounting struct {
	IfFamily         *string `protobuf:"bytes,1,opt,name=if_family" json:"if_family,omitempty"`
	FcNumber         *uint32 `protobuf:"varint,2,opt,name=fc_number" json:"fc_number,omitempty"`
	IfPackets        *uint64 `protobuf:"varint,3,opt,name=if_packets" json:"if_packets,omitempty"`
	IfOctets         *uint64 `protobuf:"varint,4,opt,name=if_octets" json:"if_octets,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ForwardingClassAccounting) Reset()                    { *m = ForwardingClassAccounting{} }
func (m *ForwardingClassAccounting) String() string            { return proto.CompactTextString(m) }
func (*ForwardingClassAccounting) ProtoMessage()               {}
func (*ForwardingClassAccounting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ForwardingClassAccounting) GetIfFamily() string {
	if m != nil && m.IfFamily != nil {
		return *m.IfFamily
	}
	return ""
}

func (m *ForwardingClassAccounting) GetFcNumber() uint32 {
	if m != nil && m.FcNumber != nil {
		return *m.FcNumber
	}
	return 0
}

func (m *ForwardingClassAccounting) GetIfPackets() uint64 {
	if m != nil && m.IfPackets != nil {
		return *m.IfPackets
	}
	return 0
}

func (m *ForwardingClassAccounting) GetIfOctets() uint64 {
	if m != nil && m.IfOctets != nil {
		return *m.IfOctets
	}
	return 0
}

type LogicalInterfaceQueueStats struct {
	QueueNumber            *uint32 `protobuf:"varint,1,opt,name=queue_number" json:"queue_number,omitempty"`
	Packets                *uint64 `protobuf:"varint,2,opt,name=packets" json:"packets,omitempty"`
	Bytes                  *uint64 `protobuf:"varint,3,opt,name=bytes" json:"bytes,omitempty"`
	TailDropPackets        *uint64 `protobuf:"varint,4,opt,name=tail_drop_packets" json:"tail_drop_packets,omitempty"`
	RateLimitDropPackets   *uint64 `protobuf:"varint,5,opt,name=rate_limit_drop_packets" json:"rate_limit_drop_packets,omitempty"`
	RateLimitDropBytes     *uint64 `protobuf:"varint,6,opt,name=rate_limit_drop_bytes" json:"rate_limit_drop_bytes,omitempty"`
	RedDropPackets         *uint64 `protobuf:"varint,7,opt,name=red_drop_packets" json:"red_drop_packets,omitempty"`
	RedDropBytes           *uint64 `protobuf:"varint,8,opt,name=red_drop_bytes" json:"red_drop_bytes,omitempty"`
	AverageBufferOccupancy *uint64 `protobuf:"varint,9,opt,name=average_buffer_occupancy" json:"average_buffer_occupancy,omitempty"`
	CurrentBufferOccupancy *uint64 `protobuf:"varint,10,opt,name=current_buffer_occupancy" json:"current_buffer_occupancy,omitempty"`
	PeakBufferOccupancy    *uint64 `protobuf:"varint,11,opt,name=peak_buffer_occupancy" json:"peak_buffer_occupancy,omitempty"`
	AllocatedBufferSize    *uint64 `protobuf:"varint,12,opt,name=allocated_buffer_size" json:"allocated_buffer_size,omitempty"`
	XXX_unrecognized       []byte  `json:"-"`
}

func (m *LogicalInterfaceQueueStats) Reset()                    { *m = LogicalInterfaceQueueStats{} }
func (m *LogicalInterfaceQueueStats) String() string            { return proto.CompactTextString(m) }
func (*LogicalInterfaceQueueStats) ProtoMessage()               {}
func (*LogicalInterfaceQueueStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LogicalInterfaceQueueStats) GetQueueNumber() uint32 {
	if m != nil && m.QueueNumber != nil {
		return *m.QueueNumber
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetPackets() uint64 {
	if m != nil && m.Packets != nil {
		return *m.Packets
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetBytes() uint64 {
	if m != nil && m.Bytes != nil {
		return *m.Bytes
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetTailDropPackets() uint64 {
	if m != nil && m.TailDropPackets != nil {
		return *m.TailDropPackets
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetRateLimitDropPackets() uint64 {
	if m != nil && m.RateLimitDropPackets != nil {
		return *m.RateLimitDropPackets
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetRateLimitDropBytes() uint64 {
	if m != nil && m.RateLimitDropBytes != nil {
		return *m.RateLimitDropBytes
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetRedDropPackets() uint64 {
	if m != nil && m.RedDropPackets != nil {
		return *m.RedDropPackets
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetRedDropBytes() uint64 {
	if m != nil && m.RedDropBytes != nil {
		return *m.RedDropBytes
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetAverageBufferOccupancy() uint64 {
	if m != nil && m.AverageBufferOccupancy != nil {
		return *m.AverageBufferOccupancy
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetCurrentBufferOccupancy() uint64 {
	if m != nil && m.CurrentBufferOccupancy != nil {
		return *m.CurrentBufferOccupancy
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetPeakBufferOccupancy() uint64 {
	if m != nil && m.PeakBufferOccupancy != nil {
		return *m.PeakBufferOccupancy
	}
	return 0
}

func (m *LogicalInterfaceQueueStats) GetAllocatedBufferSize() uint64 {
	if m != nil && m.AllocatedBufferSize != nil {
		return *m.AllocatedBufferSize
	}
	return 0
}

var E_JnprLogicalInterfaceExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*LogicalPort)(nil),
	Field:         7,
	Name:          "jnprLogicalInterfaceExt",
	Tag:           "bytes,7,opt,name=jnprLogicalInterfaceExt",
	Filename:      "logical_port.proto",
}

func init() {
	proto.RegisterType((*LogicalPort)(nil), "LogicalPort")
	proto.RegisterType((*LogicalInterfaceInfo)(nil), "LogicalInterfaceInfo")
	proto.RegisterType((*IngressInterfaceStats)(nil), "IngressInterfaceStats")
	proto.RegisterType((*EgressInterfaceStats)(nil), "EgressInterfaceStats")
	proto.RegisterType((*OperationalState)(nil), "OperationalState")
	proto.RegisterType((*ForwardingClassAccounting)(nil), "ForwardingClassAccounting")
	proto.RegisterType((*LogicalInterfaceQueueStats)(nil), "logicalInterfaceQueueStats")
	proto.RegisterExtension(E_JnprLogicalInterfaceExt)
}

func init() { proto.RegisterFile("logical_port.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0xdd, 0x4e, 0xdb, 0x4a,
	0x10, 0xc7, 0xe5, 0x84, 0x90, 0x30, 0x49, 0x10, 0x18, 0x12, 0x4c, 0x38, 0x9c, 0x63, 0xe5, 0xa0,
	0x36, 0x52, 0x85, 0x2b, 0x71, 0xd1, 0x4a, 0x55, 0x2f, 0xfa, 0x21, 0x90, 0xa8, 0xaa, 0x7e, 0x88,
	0x07, 0x58, 0x2d, 0xeb, 0x71, 0xd8, 0x62, 0xef, 0x6e, 0x77, 0xd7, 0x40, 0x7a, 0x59, 0xf5, 0xb6,
	0x8f, 0xd3, 0xeb, 0x3e, 0x45, 0xdf, 0xa7, 0xb2, 0x1d, 0x83, 0xf3, 0xd1, 0xf6, 0xb6, 0xb7, 0x33,
	0xbf, 0xd9, 0x99, 0xbf, 0xff, 0xb3, 0x6b, 0x70, 0x63, 0x39, 0xe6, 0x8c, 0xc6, 0x44, 0x49, 0x6d,
	0x03, 0xa5, 0xa5, 0x95, 0x83, 0x2d, 0x8b, 0x31, 0x26, 0x68, 0xf5, 0x84, 0x58, 0xa9, 0x8a, 0xe0,
	0xf0, 0x29, 0xb4, 0x5f, 0x17, 0xe8, 0x3b, 0xa9, 0xad, 0x7b, 0x08, 0xeb, 0x5c, 0x58, 0xd4, 0x11,
	0x65, 0x48, 0xb8, 0x88, 0xa4, 0xe7, 0xf8, 0xf5, 0x51, 0xfb, 0xa8, 0x17, 0x4c, 0xa9, 0xd3, 0x32,
	0x7b, 0x2a, 0x22, 0x39, 0xfc, 0x51, 0x87, 0xed, 0x65, 0x09, 0xb7, 0x0f, 0x4d, 0x1e, 0x11, 0x41,
	0x13, 0xf4, 0x1c, 0xbf, 0x36, 0x5a, 0x7b, 0xd1, 0xf8, 0xfc, 0xac, 0xd6, 0x72, 0x5c, 0x0f, 0xd6,
	0xb8, 0xe0, 0x96, 0x58, 0x9e, 0xa0, 0x57, 0xf3, 0x6b, 0xa3, 0x95, 0x3c, 0xb3, 0xe1, 0xb8, 0xff,
	0x40, 0xd7, 0x88, 0x44, 0x11, 0x1e, 0x11, 0x2e, 0x42, 0xbc, 0xf1, 0xea, 0xbe, 0x33, 0xea, 0x96,
	0x75, 0xfb, 0xb0, 0xae, 0xa8, 0x46, 0x61, 0x09, 0xc5, 0xe2, 0xd8, 0x15, 0xdf, 0xb9, 0x3b, 0xf6,
	0x10, 0xba, 0x5c, 0x8c, 0x35, 0x1a, 0x43, 0x8c, 0xa5, 0xd6, 0x78, 0x0d, 0xdf, 0x19, 0xb5, 0x8f,
	0xfa, 0xc1, 0x69, 0x11, 0xbd, 0x1d, 0xee, 0x2c, 0xcb, 0xba, 0x0f, 0xa0, 0x83, 0x55, 0x7a, 0x35,
	0xa7, 0x7b, 0xc1, 0xf1, 0x32, 0xf8, 0x7f, 0x68, 0x49, 0x95, 0x83, 0xe8, 0x35, 0x73, 0x70, 0x33,
	0x78, 0xab, 0x50, 0x53, 0xcb, 0xa5, 0xa0, 0x71, 0x06, 0xa1, 0xfb, 0x2f, 0xf4, 0x69, 0x98, 0x70,
	0xc1, 0x8d, 0xd5, 0x94, 0x59, 0x7e, 0x85, 0x79, 0x45, 0x6a, 0xbc, 0x56, 0x36, 0xa7, 0xbb, 0x05,
	0xed, 0x10, 0x0d, 0xd3, 0x5c, 0x65, 0x55, 0xde, 0x5a, 0x19, 0x8c, 0xa9, 0xb1, 0x84, 0x5d, 0x50,
	0x31, 0x46, 0x0f, 0x32, 0xc1, 0xae, 0x0b, 0x70, 0xc1, 0xc7, 0x17, 0xc4, 0x28, 0xc4, 0xd0, 0x6b,
	0xe7, 0xb1, 0xc7, 0xe0, 0x96, 0xf2, 0x3e, 0xa6, 0x98, 0x4e, 0x9d, 0xe9, 0xe4, 0xce, 0xec, 0x05,
	0xf1, 0x9c, 0x01, 0xef, 0x33, 0xa4, 0x98, 0xfd, 0x11, 0x6c, 0xe2, 0x42, 0x5d, 0xf7, 0x8f, 0x75,
	0xc3, 0xef, 0x0e, 0xf4, 0x96, 0x7f, 0xba, 0x5d, 0x00, 0x1e, 0x11, 0x45, 0xd9, 0x25, 0x5a, 0x93,
	0x7b, 0x5b, 0x38, 0xe8, 0x15, 0xde, 0x46, 0x44, 0x32, 0x9b, 0x65, 0x6a, 0xd5, 0xcc, 0x7f, 0xb0,
	0xc1, 0x23, 0x92, 0xb2, 0x4c, 0x6c, 0x59, 0x9a, 0xd9, 0x3b, 0x07, 0x24, 0x33, 0xc0, 0x4a, 0x15,
	0x78, 0x08, 0x6d, 0x1e, 0x91, 0x88, 0xdd, 0xda, 0x9b, 0x49, 0x18, 0x04, 0x27, 0x52, 0x5f, 0x53,
	0x1d, 0x72, 0x31, 0x7e, 0x19, 0x53, 0x63, 0x9e, 0x33, 0x26, 0x53, 0x61, 0xb9, 0x18, 0x0f, 0xbf,
	0x3a, 0xb0, 0x7d, 0xfc, 0xf7, 0x08, 0x18, 0x06, 0xb0, 0xb1, 0xb0, 0x34, 0x03, 0x70, 0xe5, 0x5d,
	0xac, 0x5c, 0x18, 0x27, 0xdb, 0x8d, 0xe1, 0x17, 0x07, 0x76, 0x7f, 0xa9, 0x6e, 0x3a, 0x69, 0x44,
	0x13, 0x1e, 0x4f, 0x8a, 0x82, 0xca, 0x05, 0x8b, 0x18, 0x11, 0x69, 0x72, 0x8e, 0xda, 0xab, 0x55,
	0xaf, 0xd0, 0xac, 0xf0, 0x99, 0xe9, 0x67, 0x84, 0xcf, 0x8c, 0xfd, 0xad, 0x0e, 0x83, 0xdf, 0xec,
	0xd7, 0x1e, 0x74, 0x8a, 0xc5, 0x9a, 0x36, 0x74, 0xaa, 0x0d, 0xfb, 0xd0, 0x2c, 0xbb, 0xd5, 0xaa,
	0xdd, 0xb6, 0xa1, 0x71, 0x3e, 0xb1, 0x38, 0x37, 0x83, 0x0f, 0x9b, 0x96, 0xf2, 0x98, 0x84, 0x5a,
	0xaa, 0xe5, 0x3b, 0x70, 0x0f, 0x76, 0x34, 0xb5, 0x48, 0x62, 0x9e, 0x70, 0x3b, 0xcb, 0x35, 0xaa,
	0xdc, 0x01, 0xf4, 0xe6, 0xb9, 0xa2, 0xdf, 0xea, 0x9c, 0x63, 0x1a, 0xc3, 0xd9, 0x63, 0x9a, 0x55,
	0x60, 0x1f, 0xd6, 0x6f, 0x81, 0xa2, 0xbe, 0x55, 0x4d, 0xdf, 0x07, 0x8f, 0x5e, 0xa1, 0xa6, 0x63,
	0x24, 0xe7, 0x69, 0x14, 0xa1, 0x26, 0x92, 0xb1, 0x54, 0x51, 0xc1, 0x26, 0xf9, 0xf5, 0x2e, 0x40,
	0x3f, 0x07, 0x59, 0xaa, 0xf3, 0xb7, 0x6b, 0x01, 0x84, 0x2a, 0x78, 0x00, 0x3d, 0x85, 0xf4, 0x72,
	0x91, 0x6a, 0xcf, 0x51, 0x34, 0x8e, 0x25, 0xa3, 0x16, 0xc3, 0x12, 0x35, 0xfc, 0x13, 0x7a, 0x9d,
	0x0a, 0xf5, 0xe4, 0x04, 0x76, 0x3e, 0x08, 0xa5, 0xe7, 0xdf, 0xe6, 0xe3, 0x1b, 0xeb, 0xee, 0x04,
	0xaf, 0x52, 0xc1, 0x15, 0xea, 0x37, 0x68, 0xaf, 0xa5, 0xbe, 0x34, 0x67, 0x28, 0x8c, 0xd4, 0x66,
	0xfa, 0xb8, 0x75, 0x82, 0xca, 0xff, 0xe0, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xaa, 0x12,
	0x9e, 0x48, 0x06, 0x00, 0x00,
}
