// Code generated by protoc-gen-go. DO NOT EDIT.
// source: npu_utilization.proto

/*
Package npu_utilization is a generated protocol buffer package.

It is generated from these files:
	npu_utilization.proto

It has these top-level messages:
	NetworkProcessorUtilization
	Utilization
	MemoryLoad
	PacketLoad
*/
package npu_utilization

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetworkProcessorUtilization struct {
	NpuUtilStats     []*Utilization `protobuf:"bytes,1,rep,name=npu_util_stats" json:"npu_util_stats,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *NetworkProcessorUtilization) Reset()                    { *m = NetworkProcessorUtilization{} }
func (m *NetworkProcessorUtilization) String() string            { return proto.CompactTextString(m) }
func (*NetworkProcessorUtilization) ProtoMessage()               {}
func (*NetworkProcessorUtilization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NetworkProcessorUtilization) GetNpuUtilStats() []*Utilization {
	if m != nil {
		return m.NpuUtilStats
	}
	return nil
}

type Utilization struct {
	Identifier       *string       `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	Utilization      *uint32       `protobuf:"varint,2,opt,name=utilization" json:"utilization,omitempty"`
	Packets          []*PacketLoad `protobuf:"bytes,3,rep,name=packets" json:"packets,omitempty"`
	Memory           []*MemoryLoad `protobuf:"bytes,4,rep,name=memory" json:"memory,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Utilization) Reset()                    { *m = Utilization{} }
func (m *Utilization) String() string            { return proto.CompactTextString(m) }
func (*Utilization) ProtoMessage()               {}
func (*Utilization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Utilization) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *Utilization) GetUtilization() uint32 {
	if m != nil && m.Utilization != nil {
		return *m.Utilization
	}
	return 0
}

func (m *Utilization) GetPackets() []*PacketLoad {
	if m != nil {
		return m.Packets
	}
	return nil
}

func (m *Utilization) GetMemory() []*MemoryLoad {
	if m != nil {
		return m.Memory
	}
	return nil
}

type MemoryLoad struct {
	Name                *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	AverageUtil         *uint32 `protobuf:"varint,2,opt,name=average_util" json:"average_util,omitempty"`
	HighestUtil         *uint32 `protobuf:"varint,3,opt,name=highest_util" json:"highest_util,omitempty"`
	LowestUtil          *uint32 `protobuf:"varint,4,opt,name=lowest_util" json:"lowest_util,omitempty"`
	AverageCacheHitRate *uint32 `protobuf:"varint,5,opt,name=average_cache_hit_rate" json:"average_cache_hit_rate,omitempty"`
	HighestCacheHitRate *uint32 `protobuf:"varint,6,opt,name=highest_cache_hit_rate" json:"highest_cache_hit_rate,omitempty"`
	LowestCacheHitRate  *uint32 `protobuf:"varint,7,opt,name=lowest_cache_hit_rate" json:"lowest_cache_hit_rate,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *MemoryLoad) Reset()                    { *m = MemoryLoad{} }
func (m *MemoryLoad) String() string            { return proto.CompactTextString(m) }
func (*MemoryLoad) ProtoMessage()               {}
func (*MemoryLoad) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MemoryLoad) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MemoryLoad) GetAverageUtil() uint32 {
	if m != nil && m.AverageUtil != nil {
		return *m.AverageUtil
	}
	return 0
}

func (m *MemoryLoad) GetHighestUtil() uint32 {
	if m != nil && m.HighestUtil != nil {
		return *m.HighestUtil
	}
	return 0
}

func (m *MemoryLoad) GetLowestUtil() uint32 {
	if m != nil && m.LowestUtil != nil {
		return *m.LowestUtil
	}
	return 0
}

func (m *MemoryLoad) GetAverageCacheHitRate() uint32 {
	if m != nil && m.AverageCacheHitRate != nil {
		return *m.AverageCacheHitRate
	}
	return 0
}

func (m *MemoryLoad) GetHighestCacheHitRate() uint32 {
	if m != nil && m.HighestCacheHitRate != nil {
		return *m.HighestCacheHitRate
	}
	return 0
}

func (m *MemoryLoad) GetLowestCacheHitRate() uint32 {
	if m != nil && m.LowestCacheHitRate != nil {
		return *m.LowestCacheHitRate
	}
	return 0
}

type PacketLoad struct {
	Identifier                   *string `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	Rate                         *uint64 `protobuf:"varint,2,opt,name=rate" json:"rate,omitempty"`
	AverageInstructionsPerPacket *uint32 `protobuf:"varint,3,opt,name=average_instructions_per_packet" json:"average_instructions_per_packet,omitempty"`
	AverageWaitCyclesPerPacket   *uint32 `protobuf:"varint,4,opt,name=average_wait_cycles_per_packet" json:"average_wait_cycles_per_packet,omitempty"`
	AverageCyclesPerPacket       *uint32 `protobuf:"varint,5,opt,name=average_cycles_per_packet" json:"average_cycles_per_packet,omitempty"`
	XXX_unrecognized             []byte  `json:"-"`
}

func (m *PacketLoad) Reset()                    { *m = PacketLoad{} }
func (m *PacketLoad) String() string            { return proto.CompactTextString(m) }
func (*PacketLoad) ProtoMessage()               {}
func (*PacketLoad) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PacketLoad) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *PacketLoad) GetRate() uint64 {
	if m != nil && m.Rate != nil {
		return *m.Rate
	}
	return 0
}

func (m *PacketLoad) GetAverageInstructionsPerPacket() uint32 {
	if m != nil && m.AverageInstructionsPerPacket != nil {
		return *m.AverageInstructionsPerPacket
	}
	return 0
}

func (m *PacketLoad) GetAverageWaitCyclesPerPacket() uint32 {
	if m != nil && m.AverageWaitCyclesPerPacket != nil {
		return *m.AverageWaitCyclesPerPacket
	}
	return 0
}

func (m *PacketLoad) GetAverageCyclesPerPacket() uint32 {
	if m != nil && m.AverageCyclesPerPacket != nil {
		return *m.AverageCyclesPerPacket
	}
	return 0
}

var E_JnprNpuUtilizationExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*NetworkProcessorUtilization)(nil),
	Field:         12,
	Name:          "jnpr_npu_utilization_ext",
	Tag:           "bytes,12,opt,name=jnpr_npu_utilization_ext",
	Filename:      "npu_utilization.proto",
}

func init() {
	proto.RegisterType((*NetworkProcessorUtilization)(nil), "NetworkProcessorUtilization")
	proto.RegisterType((*Utilization)(nil), "Utilization")
	proto.RegisterType((*MemoryLoad)(nil), "MemoryLoad")
	proto.RegisterType((*PacketLoad)(nil), "PacketLoad")
	proto.RegisterExtension(E_JnprNpuUtilizationExt)
}

func init() { proto.RegisterFile("npu_utilization.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x95, 0xbb, 0xa1, 0x55, 0x27, 0x81, 0x83, 0xb7, 0x05, 0x43, 0x4b, 0x09, 0x11, 0x82, 0x9c,
	0x72, 0xe8, 0x91, 0x2b, 0x37, 0x04, 0xa8, 0x12, 0x42, 0x1c, 0x2d, 0x2b, 0x1d, 0x36, 0x66, 0x13,
	0x3b, 0xd8, 0x13, 0x96, 0xe5, 0x73, 0xf8, 0x0c, 0xbe, 0x0e, 0xc5, 0x49, 0x76, 0xc3, 0x82, 0x7a,
	0xf4, 0x7b, 0x6f, 0x9e, 0xdf, 0x1b, 0x0d, 0x9c, 0x9b, 0xb6, 0x93, 0x1d, 0xe9, 0x5a, 0xff, 0x54,
	0xa4, 0xad, 0x29, 0x5a, 0x67, 0xc9, 0x3e, 0x59, 0x12, 0xd6, 0xd8, 0x20, 0xb9, 0xad, 0x24, 0xdb,
	0x0e, 0x60, 0xf6, 0x06, 0x2e, 0x3e, 0x20, 0x6d, 0xac, 0x5b, 0xdf, 0x38, 0x5b, 0xa2, 0xf7, 0xd6,
	0x7d, 0xda, 0x4f, 0xf2, 0x17, 0xf0, 0x60, 0x32, 0x93, 0x9e, 0x14, 0x79, 0xc1, 0xd2, 0x45, 0x1e,
	0x5f, 0x27, 0xc5, 0x4c, 0x95, 0x7d, 0x83, 0x78, 0x3e, 0xc4, 0x01, 0xf4, 0x2d, 0x1a, 0xd2, 0x5f,
	0x34, 0x3a, 0xc1, 0xd2, 0xa3, 0xfc, 0x94, 0x2f, 0x21, 0x9e, 0x25, 0x12, 0x47, 0x29, 0xcb, 0xef,
	0xf3, 0x4b, 0x38, 0x69, 0x55, 0xb9, 0x46, 0xf2, 0x62, 0x11, 0x6c, 0xe3, 0xe2, 0x26, 0xbc, 0xdf,
	0x59, 0x75, 0xcb, 0x2f, 0xe0, 0xb8, 0xc1, 0xc6, 0xba, 0xad, 0x88, 0x46, 0xf2, 0x7d, 0x78, 0xf6,
	0x64, 0xf6, 0x9b, 0x01, 0xec, 0x9f, 0x3c, 0x81, 0xc8, 0xa8, 0x06, 0x05, 0x4b, 0x59, 0x7e, 0xca,
	0xcf, 0x20, 0x51, 0xdf, 0xd1, 0xa9, 0x15, 0x86, 0xe4, 0xe3, 0x6f, 0x67, 0x90, 0x54, 0x7a, 0x55,
	0xa1, 0xa7, 0x01, 0x5d, 0x04, 0x74, 0x09, 0x71, 0x6d, 0x37, 0x3b, 0x30, 0x0a, 0xe0, 0x15, 0x3c,
	0x9c, 0x0c, 0x4a, 0x55, 0x56, 0x28, 0x2b, 0x4d, 0xd2, 0x29, 0x42, 0x71, 0x6f, 0xe2, 0x27, 0xab,
	0x03, 0xfe, 0x38, 0xf0, 0x4f, 0xe1, 0x7c, 0x34, 0x3d, 0xa0, 0x4f, 0x7a, 0x3a, 0xfb, 0xc5, 0x00,
	0x66, 0x45, 0xff, 0xb7, 0xaf, 0x04, 0xa2, 0x30, 0xd0, 0x47, 0x8f, 0xf8, 0x2b, 0x78, 0x36, 0xe5,
	0xd1, 0xc6, 0x93, 0xeb, 0xca, 0x7e, 0x8b, 0x5e, 0xb6, 0xe8, 0xe4, 0xb0, 0xc1, 0xb1, 0xcd, 0x4b,
	0xb8, 0x9a, 0x84, 0x1b, 0xa5, 0x49, 0x96, 0xdb, 0xb2, 0xc6, 0xbf, 0x74, 0x43, 0xc1, 0xe7, 0xf0,
	0x78, 0x57, 0xf0, 0x1f, 0x49, 0xe8, 0xf8, 0xfa, 0x33, 0x88, 0xaf, 0xa6, 0x75, 0xf2, 0xe0, 0x98,
	0x24, 0xfe, 0x20, 0xfe, 0xa8, 0x78, 0xdb, 0x19, 0xdd, 0xa2, 0x1b, 0x6f, 0xc7, 0x7f, 0x44, 0xe3,
	0xad, 0xf3, 0x22, 0x49, 0x59, 0x1e, 0x5f, 0x5f, 0x16, 0x77, 0xdc, 0xd4, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x51, 0xe9, 0xd3, 0x84, 0x9f, 0x02, 0x00, 0x00,
}
