// Code generated by protoc-gen-go. DO NOT EDIT.
// source: npu_memory_utilization.proto

/*
Package npu_memory_utilization is a generated protocol buffer package.

It is generated from these files:
	npu_memory_utilization.proto

It has these top-level messages:
	NetworkProcessorMemoryUtilization
	NpuMemory
	NpuMemorySummary
	NpuMemoryPartition
*/
package npu_memory_utilization

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetworkProcessorMemoryUtilization struct {
	MemoryStats      []*NpuMemory `protobuf:"bytes,1,rep,name=memory_stats" json:"memory_stats,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *NetworkProcessorMemoryUtilization) Reset()         { *m = NetworkProcessorMemoryUtilization{} }
func (m *NetworkProcessorMemoryUtilization) String() string { return proto.CompactTextString(m) }
func (*NetworkProcessorMemoryUtilization) ProtoMessage()    {}
func (*NetworkProcessorMemoryUtilization) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *NetworkProcessorMemoryUtilization) GetMemoryStats() []*NpuMemory {
	if m != nil {
		return m.MemoryStats
	}
	return nil
}

type NpuMemory struct {
	Identifier       *string               `protobuf:"bytes,1,req,name=identifier" json:"identifier,omitempty"`
	Summary          []*NpuMemorySummary   `protobuf:"bytes,2,rep,name=summary" json:"summary,omitempty"`
	Partition        []*NpuMemoryPartition `protobuf:"bytes,3,rep,name=partition" json:"partition,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *NpuMemory) Reset()                    { *m = NpuMemory{} }
func (m *NpuMemory) String() string            { return proto.CompactTextString(m) }
func (*NpuMemory) ProtoMessage()               {}
func (*NpuMemory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NpuMemory) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

func (m *NpuMemory) GetSummary() []*NpuMemorySummary {
	if m != nil {
		return m.Summary
	}
	return nil
}

func (m *NpuMemory) GetPartition() []*NpuMemoryPartition {
	if m != nil {
		return m.Partition
	}
	return nil
}

type NpuMemorySummary struct {
	ResourceName     *string `protobuf:"bytes,1,opt,name=resource_name" json:"resource_name,omitempty"`
	Size             *uint64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Allocated        *uint64 `protobuf:"varint,3,opt,name=allocated" json:"allocated,omitempty"`
	Utilization      *int32  `protobuf:"varint,4,opt,name=utilization" json:"utilization,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NpuMemorySummary) Reset()                    { *m = NpuMemorySummary{} }
func (m *NpuMemorySummary) String() string            { return proto.CompactTextString(m) }
func (*NpuMemorySummary) ProtoMessage()               {}
func (*NpuMemorySummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NpuMemorySummary) GetResourceName() string {
	if m != nil && m.ResourceName != nil {
		return *m.ResourceName
	}
	return ""
}

func (m *NpuMemorySummary) GetSize() uint64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *NpuMemorySummary) GetAllocated() uint64 {
	if m != nil && m.Allocated != nil {
		return *m.Allocated
	}
	return 0
}

func (m *NpuMemorySummary) GetUtilization() int32 {
	if m != nil && m.Utilization != nil {
		return *m.Utilization
	}
	return 0
}

type NpuMemoryPartition struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ApplicationName  *string `protobuf:"bytes,2,opt,name=application_name" json:"application_name,omitempty"`
	BytesAllocated   *uint32 `protobuf:"varint,3,opt,name=bytes_allocated" json:"bytes_allocated,omitempty"`
	AllocationCount  *uint32 `protobuf:"varint,4,opt,name=allocation_count" json:"allocation_count,omitempty"`
	FreeCount        *uint32 `protobuf:"varint,5,opt,name=free_count" json:"free_count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NpuMemoryPartition) Reset()                    { *m = NpuMemoryPartition{} }
func (m *NpuMemoryPartition) String() string            { return proto.CompactTextString(m) }
func (*NpuMemoryPartition) ProtoMessage()               {}
func (*NpuMemoryPartition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NpuMemoryPartition) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NpuMemoryPartition) GetApplicationName() string {
	if m != nil && m.ApplicationName != nil {
		return *m.ApplicationName
	}
	return ""
}

func (m *NpuMemoryPartition) GetBytesAllocated() uint32 {
	if m != nil && m.BytesAllocated != nil {
		return *m.BytesAllocated
	}
	return 0
}

func (m *NpuMemoryPartition) GetAllocationCount() uint32 {
	if m != nil && m.AllocationCount != nil {
		return *m.AllocationCount
	}
	return 0
}

func (m *NpuMemoryPartition) GetFreeCount() uint32 {
	if m != nil && m.FreeCount != nil {
		return *m.FreeCount
	}
	return 0
}

var E_NpuMemoryExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*NetworkProcessorMemoryUtilization)(nil),
	Field:         11,
	Name:          "npu_memory_ext",
	Tag:           "bytes,11,opt,name=npu_memory_ext",
	Filename:      "npu_memory_utilization.proto",
}

func init() {
	proto.RegisterType((*NetworkProcessorMemoryUtilization)(nil), "NetworkProcessorMemoryUtilization")
	proto.RegisterType((*NpuMemory)(nil), "NpuMemory")
	proto.RegisterType((*NpuMemorySummary)(nil), "NpuMemorySummary")
	proto.RegisterType((*NpuMemoryPartition)(nil), "NpuMemoryPartition")
	proto.RegisterExtension(E_NpuMemoryExt)
}

func init() { proto.RegisterFile("npu_memory_utilization.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x49, 0xb7, 0x21, 0xfd, 0xba, 0xe9, 0x96, 0x21, 0x0b, 0xe2, 0xa1, 0xf6, 0x20, 0x3d,
	0xf5, 0xb0, 0xa3, 0x77, 0x2f, 0x82, 0x63, 0x30, 0x3c, 0x97, 0xd8, 0x7d, 0x83, 0xb0, 0xb6, 0x09,
	0xc9, 0x57, 0xb4, 0xbb, 0xfa, 0x8f, 0x4b, 0xd3, 0xe9, 0x26, 0x3b, 0x78, 0xcc, 0xfb, 0xde, 0xef,
	0x3d, 0xc8, 0x83, 0xfb, 0xda, 0x34, 0x79, 0x85, 0x95, 0xb6, 0x6d, 0xde, 0x90, 0x2a, 0xd5, 0x41,
	0x92, 0xd2, 0x75, 0x66, 0xac, 0x26, 0x7d, 0x37, 0x27, 0x2c, 0xb1, 0x42, 0xb2, 0x6d, 0x4e, 0xda,
	0xf4, 0x62, 0xf2, 0x0c, 0x0f, 0x2b, 0xa4, 0x0f, 0x6d, 0xf7, 0x6b, 0xab, 0x0b, 0x74, 0x4e, 0xdb,
	0x57, 0x1f, 0xf0, 0x76, 0xe2, 0x79, 0x0c, 0xe3, 0x63, 0xaa, 0x23, 0x49, 0x4e, 0xb0, 0x78, 0x90,
	0x46, 0x4b, 0xc8, 0x56, 0xa6, 0xe9, 0xcd, 0xc9, 0x1e, 0xc2, 0xdf, 0x07, 0xe7, 0x00, 0x6a, 0x8b,
	0x35, 0xa9, 0x9d, 0x42, 0x2b, 0x58, 0x1c, 0xa4, 0x21, 0x4f, 0xe0, 0xca, 0x35, 0x55, 0x25, 0x6d,
	0x2b, 0x02, 0x4f, 0xcf, 0x4e, 0xf4, 0xa6, 0x3f, 0xf0, 0x47, 0x08, 0x8d, 0xb4, 0xa4, 0xba, 0x4e,
	0x31, 0xf0, 0xae, 0xf9, 0xc9, 0xb5, 0xfe, 0x39, 0x25, 0x39, 0x4c, 0x2f, 0xd8, 0x5b, 0x98, 0x58,
	0x74, 0xba, 0xb1, 0x05, 0xe6, 0xb5, 0xac, 0x50, 0xb0, 0x98, 0xa5, 0x21, 0x1f, 0xc3, 0xd0, 0xa9,
	0x03, 0x8a, 0x20, 0x66, 0xe9, 0x90, 0xcf, 0x20, 0x94, 0x65, 0xa9, 0x0b, 0x49, 0xb8, 0x15, 0x03,
	0x2f, 0xcd, 0x21, 0x3a, 0xfb, 0x29, 0x31, 0x8c, 0x59, 0x3a, 0x4a, 0xbe, 0x18, 0xf0, 0xcb, 0xde,
	0x2e, 0xec, 0x2c, 0x5a, 0xc0, 0x54, 0x1a, 0x53, 0xaa, 0xc2, 0x93, 0x7d, 0x69, 0xe0, 0x2f, 0x0b,
	0xb8, 0x79, 0x6f, 0x09, 0x5d, 0xfe, 0xb7, 0x6c, 0xe2, 0x91, 0x5e, 0xea, 0x88, 0x42, 0x37, 0x35,
	0xf9, 0xc6, 0x49, 0xf7, 0x65, 0x3b, 0x8b, 0x78, 0xd4, 0x46, 0x9d, 0xf6, 0xb4, 0x81, 0xeb, 0xb3,
	0x3d, 0xf1, 0x93, 0xf8, 0x22, 0x7b, 0x69, 0x6a, 0x65, 0xd0, 0x1e, 0x27, 0x73, 0x1b, 0xac, 0x9d,
	0xb6, 0x4e, 0x44, 0x31, 0x4b, 0xa3, 0x65, 0x92, 0xfd, 0x3b, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x67, 0x99, 0x36, 0xf2, 0x23, 0x02, 0x00, 0x00,
}
