// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packet_stats.proto

/*
Package packet_stats is a generated protocol buffer package.

It is generated from these files:
	packet_stats.proto

It has these top-level messages:
	PacketStatistics
	PacketStatsPacketForwardingEngine
	PacketStatsClass
	PacketStatsCounter
*/
package packet_stats

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PacketStatistics struct {
	PacketStats      []*PacketStatsClass                  `protobuf:"bytes,1,rep,name=packet_stats" json:"packet_stats,omitempty"`
	PacketStatsPfe   []*PacketStatsPacketForwardingEngine `protobuf:"bytes,2,rep,name=packet_stats_pfe" json:"packet_stats_pfe,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *PacketStatistics) Reset()                    { *m = PacketStatistics{} }
func (m *PacketStatistics) String() string            { return proto.CompactTextString(m) }
func (*PacketStatistics) ProtoMessage()               {}
func (*PacketStatistics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PacketStatistics) GetPacketStats() []*PacketStatsClass {
	if m != nil {
		return m.PacketStats
	}
	return nil
}

func (m *PacketStatistics) GetPacketStatsPfe() []*PacketStatsPacketForwardingEngine {
	if m != nil {
		return m.PacketStatsPfe
	}
	return nil
}

type PacketStatsPacketForwardingEngine struct {
	PfeIdentifier    *string             `protobuf:"bytes,1,req,name=pfe_identifier" json:"pfe_identifier,omitempty"`
	PacketStats      []*PacketStatsClass `protobuf:"bytes,2,rep,name=packet_stats" json:"packet_stats,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PacketStatsPacketForwardingEngine) Reset()         { *m = PacketStatsPacketForwardingEngine{} }
func (m *PacketStatsPacketForwardingEngine) String() string { return proto.CompactTextString(m) }
func (*PacketStatsPacketForwardingEngine) ProtoMessage()    {}
func (*PacketStatsPacketForwardingEngine) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

func (m *PacketStatsPacketForwardingEngine) GetPfeIdentifier() string {
	if m != nil && m.PfeIdentifier != nil {
		return *m.PfeIdentifier
	}
	return ""
}

func (m *PacketStatsPacketForwardingEngine) GetPacketStats() []*PacketStatsClass {
	if m != nil {
		return m.PacketStats
	}
	return nil
}

type PacketStatsClass struct {
	Name             *string             `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Counter          *PacketStatsCounter `protobuf:"bytes,2,req,name=counter" json:"counter,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PacketStatsClass) Reset()                    { *m = PacketStatsClass{} }
func (m *PacketStatsClass) String() string            { return proto.CompactTextString(m) }
func (*PacketStatsClass) ProtoMessage()               {}
func (*PacketStatsClass) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PacketStatsClass) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PacketStatsClass) GetCounter() *PacketStatsCounter {
	if m != nil {
		return m.Counter
	}
	return nil
}

type PacketStatsCounter struct {
	PacketCount      *uint64 `protobuf:"varint,1,req,name=packet_count" json:"packet_count,omitempty"`
	ByteCount        *uint64 `protobuf:"varint,2,opt,name=byte_count" json:"byte_count,omitempty"`
	PacketRate       *uint64 `protobuf:"varint,3,opt,name=packet_rate" json:"packet_rate,omitempty"`
	BitRate          *uint64 `protobuf:"varint,4,opt,name=bit_rate" json:"bit_rate,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PacketStatsCounter) Reset()                    { *m = PacketStatsCounter{} }
func (m *PacketStatsCounter) String() string            { return proto.CompactTextString(m) }
func (*PacketStatsCounter) ProtoMessage()               {}
func (*PacketStatsCounter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PacketStatsCounter) GetPacketCount() uint64 {
	if m != nil && m.PacketCount != nil {
		return *m.PacketCount
	}
	return 0
}

func (m *PacketStatsCounter) GetByteCount() uint64 {
	if m != nil && m.ByteCount != nil {
		return *m.ByteCount
	}
	return 0
}

func (m *PacketStatsCounter) GetPacketRate() uint64 {
	if m != nil && m.PacketRate != nil {
		return *m.PacketRate
	}
	return 0
}

func (m *PacketStatsCounter) GetBitRate() uint64 {
	if m != nil && m.BitRate != nil {
		return *m.BitRate
	}
	return 0
}

var E_JnprPacketStatisticsExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*PacketStatistics)(nil),
	Field:         8,
	Name:          "jnpr_packet_statistics_ext",
	Tag:           "bytes,8,opt,name=jnpr_packet_statistics_ext",
	Filename:      "packet_stats.proto",
}

func init() {
	proto.RegisterType((*PacketStatistics)(nil), "PacketStatistics")
	proto.RegisterType((*PacketStatsPacketForwardingEngine)(nil), "PacketStatsPacketForwardingEngine")
	proto.RegisterType((*PacketStatsClass)(nil), "PacketStatsClass")
	proto.RegisterType((*PacketStatsCounter)(nil), "PacketStatsCounter")
	proto.RegisterExtension(E_JnprPacketStatisticsExt)
}

func init() { proto.RegisterFile("packet_stats.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x69, 0x56, 0x70, 0xbe, 0x0d, 0x99, 0x99, 0x68, 0xd8, 0xa9, 0x16, 0xc1, 0x9e, 0x7a,
	0xd8, 0x51, 0xbc, 0x89, 0x3b, 0x78, 0x18, 0xc2, 0xfe, 0x80, 0x90, 0xb5, 0xaf, 0x23, 0x6e, 0x4b,
	0x42, 0xf2, 0xc6, 0xec, 0x7f, 0x2f, 0xb6, 0x45, 0xab, 0x43, 0xbc, 0x95, 0x5f, 0x7f, 0xef, 0xe3,
	0xfb, 0x08, 0x70, 0xa7, 0x8a, 0x2d, 0x92, 0x0c, 0xa4, 0x28, 0xe4, 0xce, 0x5b, 0xb2, 0xb3, 0x29,
	0xe1, 0x0e, 0xf7, 0x48, 0xbe, 0x96, 0x64, 0x5d, 0x0b, 0xd3, 0x1a, 0x26, 0xaf, 0x8d, 0xba, 0x22,
	0x45, 0x3a, 0x90, 0x2e, 0x02, 0xbf, 0x87, 0x71, 0xff, 0x5c, 0x44, 0xc9, 0x20, 0x1b, 0xcd, 0x2f,
	0xf3, 0x6f, 0x31, 0x3c, 0xed, 0x54, 0x08, 0xfc, 0x11, 0x26, 0x7d, 0x51, 0xba, 0x0a, 0x05, 0x6b,
	0xe4, 0xb4, 0x2f, 0xb7, 0x9f, 0x0b, 0xeb, 0x8f, 0xca, 0x97, 0xda, 0x6c, 0x9e, 0xcd, 0x46, 0x1b,
	0x4c, 0x4b, 0xb8, 0xfd, 0x57, 0xe2, 0xd7, 0x70, 0xe1, 0x2a, 0x94, 0xba, 0x44, 0x43, 0xba, 0xd2,
	0xe8, 0x45, 0x94, 0xb0, 0xec, 0xfc, 0xa4, 0x23, 0xfb, 0xa3, 0x63, 0xba, 0xe8, 0x0f, 0xec, 0x7a,
	0x8f, 0x21, 0x36, 0x6a, 0x8f, 0x5d, 0xd4, 0x1d, 0x9c, 0x15, 0xf6, 0x60, 0x08, 0xbd, 0x60, 0x09,
	0xcb, 0x46, 0xf3, 0xe9, 0x8f, 0x94, 0xf6, 0x57, 0x8a, 0xc0, 0x4f, 0x29, 0xbf, 0xfa, 0xaa, 0xd1,
	0x44, 0x34, 0x89, 0x31, 0xe7, 0x00, 0xeb, 0x9a, 0xb0, 0x63, 0x2c, 0x89, 0xb2, 0x98, 0x4f, 0x61,
	0xd4, 0x99, 0x5e, 0x11, 0x8a, 0x41, 0x03, 0x27, 0x30, 0x5c, 0xeb, 0x8e, 0xc4, 0x9f, 0xe4, 0x61,
	0x09, 0xb3, 0x37, 0xe3, 0xbc, 0xec, 0x8d, 0x6b, 0x5f, 0x45, 0xe2, 0x3b, 0xf1, 0x9b, 0xfc, 0xe5,
	0x60, 0xb4, 0x43, 0xbf, 0x44, 0x3a, 0x5a, 0xbf, 0x0d, 0x2b, 0x34, 0xc1, 0xfa, 0x20, 0x86, 0x49,
	0xf4, 0x6b, 0x7e, 0x7b, 0xf5, 0x11, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xff, 0x2b, 0x7a, 0x09, 0x02,
	0x00, 0x00,
}
