// Code generated by protoc-gen-go. DO NOT EDIT.
// source: port_exp.proto

/*
Package port_exp is a generated protocol buffer package.

It is generated from these files:
	port_exp.proto

It has these top-level messages:
	PortExp
	InterfaceExpInfos
*/
package port_exp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PortExp struct {
	InterfaceExpStats []*InterfaceExpInfos `protobuf:"bytes,1,rep,name=interfaceExp_stats" json:"interfaceExp_stats,omitempty"`
	XXX_unrecognized  []byte               `json:"-"`
}

func (m *PortExp) Reset()                    { *m = PortExp{} }
func (m *PortExp) String() string            { return proto.CompactTextString(m) }
func (*PortExp) ProtoMessage()               {}
func (*PortExp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PortExp) GetInterfaceExpStats() []*InterfaceExpInfos {
	if m != nil {
		return m.InterfaceExpStats
	}
	return nil
}

type InterfaceExpInfos struct {
	IfName              *string `protobuf:"bytes,1,req,name=if_name" json:"if_name,omitempty"`
	IfOperationalStatus *string `protobuf:"bytes,2,opt,name=if_operational_status" json:"if_operational_status,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *InterfaceExpInfos) Reset()                    { *m = InterfaceExpInfos{} }
func (m *InterfaceExpInfos) String() string            { return proto.CompactTextString(m) }
func (*InterfaceExpInfos) ProtoMessage()               {}
func (*InterfaceExpInfos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InterfaceExpInfos) GetIfName() string {
	if m != nil && m.IfName != nil {
		return *m.IfName
	}
	return ""
}

func (m *InterfaceExpInfos) GetIfOperationalStatus() string {
	if m != nil && m.IfOperationalStatus != nil {
		return *m.IfOperationalStatus
	}
	return ""
}

var E_JnprInterfaceExpExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*PortExp)(nil),
	Field:         18,
	Name:          "jnpr_interface_exp_ext",
	Tag:           "bytes,18,opt,name=jnpr_interface_exp_ext",
	Filename:      "port_exp.proto",
}

func init() {
	proto.RegisterType((*PortExp)(nil), "Port_exp")
	proto.RegisterType((*InterfaceExpInfos)(nil), "InterfaceExpInfos")
	proto.RegisterExtension(E_JnprInterfaceExpExt)
}

func init() { proto.RegisterFile("port_exp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xce, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x71, 0x52, 0x11, 0xb7, 0x59, 0x10, 0x8c, 0xb8, 0x06, 0x41, 0x08, 0x7b, 0xca, 0x29,
	0x87, 0x3d, 0xee, 0x49, 0x0a, 0x1e, 0xda, 0x83, 0x08, 0x3e, 0x40, 0x08, 0x32, 0x81, 0x68, 0x9b,
	0x09, 0x93, 0x29, 0xd6, 0xab, 0x4f, 0x2e, 0x4a, 0x15, 0xc1, 0xeb, 0x7f, 0x86, 0x8f, 0x9f, 0x3c,
	0x2f, 0x48, 0xec, 0x61, 0x29, 0xae, 0x10, 0x32, 0xde, 0x5c, 0x32, 0x8c, 0x30, 0x01, 0xd3, 0xbb,
	0x67, 0x5c, 0xe3, 0xfe, 0x28, 0x37, 0x8f, 0xeb, 0x9b, 0x72, 0x52, 0xa5, 0xcc, 0x40, 0x31, 0x3c,
	0xc3, 0xfd, 0x52, 0x7c, 0xe5, 0xc0, 0x55, 0x0b, 0x73, 0x62, 0xb7, 0x07, 0xe5, 0xfa, 0x3f, 0xa7,
	0x3e, 0x47, 0xac, 0xfb, 0x41, 0x5e, 0xfc, 0x8b, 0x6a, 0x27, 0xcf, 0x52, 0xf4, 0x39, 0x4c, 0xa0,
	0x85, 0x69, 0x6c, 0xdb, 0x9d, 0x7e, 0xdc, 0x35, 0x1b, 0xa1, 0x6e, 0xe5, 0x55, 0x8a, 0x1e, 0x0b,
	0x50, 0xe0, 0x84, 0x39, 0x8c, 0xdf, 0xf3, 0x73, 0xd5, 0x8d, 0x11, 0xb6, 0x3d, 0x76, 0x72, 0xf7,
	0x92, 0x0b, 0xf9, 0x5f, 0xc0, 0x97, 0xc8, 0xc3, 0xc2, 0xea, 0xda, 0x0d, 0x73, 0x4e, 0x05, 0xe8,
	0x01, 0xf8, 0x0d, 0xe9, 0xb5, 0x3e, 0x41, 0xae, 0x48, 0x55, 0x2b, 0x23, 0xec, 0xf6, 0xd0, 0xba,
	0x1f, 0xff, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x7a, 0x7f, 0xb1, 0xf1, 0x00, 0x00, 0x00,
}
