// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qmon.proto

/*
Package qmon is a generated protocol buffer package.

It is generated from these files:
	qmon.proto

It has these top-level messages:
	QueueMonitor
	QueueMonitorElement
	QueueMonitorDirection
	QueueMonitorStats
*/
package qmon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import telemetry_top "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueueMonitor struct {
	QueueMonitorElementInfo []*QueueMonitorElement `protobuf:"bytes,1,rep,name=queue_monitor_element_info" json:"queue_monitor_element_info,omitempty"`
	XXX_unrecognized        []byte                 `json:"-"`
}

func (m *QueueMonitor) Reset()                    { *m = QueueMonitor{} }
func (m *QueueMonitor) String() string            { return proto.CompactTextString(m) }
func (*QueueMonitor) ProtoMessage()               {}
func (*QueueMonitor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueueMonitor) GetQueueMonitorElementInfo() []*QueueMonitorElement {
	if m != nil {
		return m.QueueMonitorElementInfo
	}
	return nil
}

type QueueMonitorElement struct {
	IfName                   *string                `protobuf:"bytes,1,req,name=if_name" json:"if_name,omitempty"`
	ParentAeName             *string                `protobuf:"bytes,2,opt,name=parent_ae_name" json:"parent_ae_name,omitempty"`
	QueueMonitorStatsIngress *QueueMonitorDirection `protobuf:"bytes,3,opt,name=queue_monitor_stats_ingress" json:"queue_monitor_stats_ingress,omitempty"`
	QueueMonitorStatsEgress  *QueueMonitorDirection `protobuf:"bytes,4,opt,name=queue_monitor_stats_egress" json:"queue_monitor_stats_egress,omitempty"`
	XXX_unrecognized         []byte                 `json:"-"`
}

func (m *QueueMonitorElement) Reset()                    { *m = QueueMonitorElement{} }
func (m *QueueMonitorElement) String() string            { return proto.CompactTextString(m) }
func (*QueueMonitorElement) ProtoMessage()               {}
func (*QueueMonitorElement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueueMonitorElement) GetIfName() string {
	if m != nil && m.IfName != nil {
		return *m.IfName
	}
	return ""
}

func (m *QueueMonitorElement) GetParentAeName() string {
	if m != nil && m.ParentAeName != nil {
		return *m.ParentAeName
	}
	return ""
}

func (m *QueueMonitorElement) GetQueueMonitorStatsIngress() *QueueMonitorDirection {
	if m != nil {
		return m.QueueMonitorStatsIngress
	}
	return nil
}

func (m *QueueMonitorElement) GetQueueMonitorStatsEgress() *QueueMonitorDirection {
	if m != nil {
		return m.QueueMonitorStatsEgress
	}
	return nil
}

type QueueMonitorDirection struct {
	QueueMonitorStatsInfo []*QueueMonitorStats `protobuf:"bytes,1,rep,name=queue_monitor_stats_info" json:"queue_monitor_stats_info,omitempty"`
	XXX_unrecognized      []byte               `json:"-"`
}

func (m *QueueMonitorDirection) Reset()                    { *m = QueueMonitorDirection{} }
func (m *QueueMonitorDirection) String() string            { return proto.CompactTextString(m) }
func (*QueueMonitorDirection) ProtoMessage()               {}
func (*QueueMonitorDirection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueueMonitorDirection) GetQueueMonitorStatsInfo() []*QueueMonitorStats {
	if m != nil {
		return m.QueueMonitorStatsInfo
	}
	return nil
}

type QueueMonitorStats struct {
	QueueNumber                *uint32 `protobuf:"varint,1,req,name=queue_number" json:"queue_number,omitempty"`
	QueueId                    *uint32 `protobuf:"varint,2,req,name=queue_id" json:"queue_id,omitempty"`
	PeakBufferOccupancyBytes   *uint32 `protobuf:"varint,3,req,name=peak_buffer_occupancy_bytes" json:"peak_buffer_occupancy_bytes,omitempty"`
	PeakBufferOccupancyPercent *uint32 `protobuf:"varint,4,opt,name=peak_buffer_occupancy_percent" json:"peak_buffer_occupancy_percent,omitempty"`
	Packets                    *uint64 `protobuf:"varint,5,req,name=packets" json:"packets,omitempty"`
	Octets                     *uint64 `protobuf:"varint,6,req,name=octets" json:"octets,omitempty"`
	TailDropPackets            *uint64 `protobuf:"varint,7,req,name=tail_drop_packets" json:"tail_drop_packets,omitempty"`
	TailDropOctets             *uint64 `protobuf:"varint,8,req,name=tail_drop_octets" json:"tail_drop_octets,omitempty"`
	RedDropPacketsColor_0      *uint64 `protobuf:"varint,9,req,name=red_drop_packets_color_0" json:"red_drop_packets_color_0,omitempty"`
	RedDropOctetsColor_0       *uint64 `protobuf:"varint,10,req,name=red_drop_octets_color_0" json:"red_drop_octets_color_0,omitempty"`
	RedDropPacketsColor_1      *uint64 `protobuf:"varint,11,req,name=red_drop_packets_color_1" json:"red_drop_packets_color_1,omitempty"`
	RedDropOctetsColor_1       *uint64 `protobuf:"varint,12,req,name=red_drop_octets_color_1" json:"red_drop_octets_color_1,omitempty"`
	RedDropPacketsColor_2      *uint64 `protobuf:"varint,13,req,name=red_drop_packets_color_2" json:"red_drop_packets_color_2,omitempty"`
	RedDropOctetsColor_2       *uint64 `protobuf:"varint,14,req,name=red_drop_octets_color_2" json:"red_drop_octets_color_2,omitempty"`
	RedDropPacketsColor_3      *uint64 `protobuf:"varint,15,req,name=red_drop_packets_color_3" json:"red_drop_packets_color_3,omitempty"`
	RedDropOctetsColor_3       *uint64 `protobuf:"varint,16,req,name=red_drop_octets_color_3" json:"red_drop_octets_color_3,omitempty"`
	XXX_unrecognized           []byte  `json:"-"`
}

func (m *QueueMonitorStats) Reset()                    { *m = QueueMonitorStats{} }
func (m *QueueMonitorStats) String() string            { return proto.CompactTextString(m) }
func (*QueueMonitorStats) ProtoMessage()               {}
func (*QueueMonitorStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueueMonitorStats) GetQueueNumber() uint32 {
	if m != nil && m.QueueNumber != nil {
		return *m.QueueNumber
	}
	return 0
}

func (m *QueueMonitorStats) GetQueueId() uint32 {
	if m != nil && m.QueueId != nil {
		return *m.QueueId
	}
	return 0
}

func (m *QueueMonitorStats) GetPeakBufferOccupancyBytes() uint32 {
	if m != nil && m.PeakBufferOccupancyBytes != nil {
		return *m.PeakBufferOccupancyBytes
	}
	return 0
}

func (m *QueueMonitorStats) GetPeakBufferOccupancyPercent() uint32 {
	if m != nil && m.PeakBufferOccupancyPercent != nil {
		return *m.PeakBufferOccupancyPercent
	}
	return 0
}

func (m *QueueMonitorStats) GetPackets() uint64 {
	if m != nil && m.Packets != nil {
		return *m.Packets
	}
	return 0
}

func (m *QueueMonitorStats) GetOctets() uint64 {
	if m != nil && m.Octets != nil {
		return *m.Octets
	}
	return 0
}

func (m *QueueMonitorStats) GetTailDropPackets() uint64 {
	if m != nil && m.TailDropPackets != nil {
		return *m.TailDropPackets
	}
	return 0
}

func (m *QueueMonitorStats) GetTailDropOctets() uint64 {
	if m != nil && m.TailDropOctets != nil {
		return *m.TailDropOctets
	}
	return 0
}

func (m *QueueMonitorStats) GetRedDropPacketsColor_0() uint64 {
	if m != nil && m.RedDropPacketsColor_0 != nil {
		return *m.RedDropPacketsColor_0
	}
	return 0
}

func (m *QueueMonitorStats) GetRedDropOctetsColor_0() uint64 {
	if m != nil && m.RedDropOctetsColor_0 != nil {
		return *m.RedDropOctetsColor_0
	}
	return 0
}

func (m *QueueMonitorStats) GetRedDropPacketsColor_1() uint64 {
	if m != nil && m.RedDropPacketsColor_1 != nil {
		return *m.RedDropPacketsColor_1
	}
	return 0
}

func (m *QueueMonitorStats) GetRedDropOctetsColor_1() uint64 {
	if m != nil && m.RedDropOctetsColor_1 != nil {
		return *m.RedDropOctetsColor_1
	}
	return 0
}

func (m *QueueMonitorStats) GetRedDropPacketsColor_2() uint64 {
	if m != nil && m.RedDropPacketsColor_2 != nil {
		return *m.RedDropPacketsColor_2
	}
	return 0
}

func (m *QueueMonitorStats) GetRedDropOctetsColor_2() uint64 {
	if m != nil && m.RedDropOctetsColor_2 != nil {
		return *m.RedDropOctetsColor_2
	}
	return 0
}

func (m *QueueMonitorStats) GetRedDropPacketsColor_3() uint64 {
	if m != nil && m.RedDropPacketsColor_3 != nil {
		return *m.RedDropPacketsColor_3
	}
	return 0
}

func (m *QueueMonitorStats) GetRedDropOctetsColor_3() uint64 {
	if m != nil && m.RedDropOctetsColor_3 != nil {
		return *m.RedDropOctetsColor_3
	}
	return 0
}

var E_JnprQmonExt = &proto.ExtensionDesc{
	ExtendedType:  (*telemetry_top.JuniperNetworksSensors)(nil),
	ExtensionType: (*QueueMonitor)(nil),
	Field:         15,
	Name:          "jnpr_qmon_ext",
	Tag:           "bytes,15,opt,name=jnpr_qmon_ext",
	Filename:      "qmon.proto",
}

func init() {
	proto.RegisterType((*QueueMonitor)(nil), "QueueMonitor")
	proto.RegisterType((*QueueMonitorElement)(nil), "QueueMonitorElement")
	proto.RegisterType((*QueueMonitorDirection)(nil), "QueueMonitorDirection")
	proto.RegisterType((*QueueMonitorStats)(nil), "QueueMonitorStats")
	proto.RegisterExtension(E_JnprQmonExt)
}

func init() { proto.RegisterFile("qmon.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x49, 0xb6, 0xbb, 0x6d, 0x4f, 0xdb, 0xfd, 0x33, 0xeb, 0xb6, 0xc3, 0x16, 0x31, 0xf4,
	0x42, 0x83, 0x48, 0x71, 0xbb, 0x5e, 0xc8, 0x8a, 0x20, 0xa2, 0x20, 0xc2, 0x0a, 0xb2, 0x0f, 0x30,
	0xa4, 0xe9, 0xa9, 0x8c, 0x6d, 0x66, 0xa6, 0x93, 0x13, 0xb4, 0xb7, 0x3e, 0x98, 0xef, 0xe1, 0xdb,
	0x48, 0x32, 0xb6, 0x26, 0x1a, 0x96, 0x5c, 0xe6, 0x3b, 0xbf, 0xef, 0xc7, 0xe1, 0x30, 0x01, 0xd8,
	0x24, 0x5a, 0x4d, 0x8d, 0xd5, 0xa4, 0x2f, 0xcf, 0x09, 0xd7, 0x98, 0x20, 0xd9, 0xad, 0x20, 0x6d,
	0x5c, 0x38, 0xf9, 0x00, 0xfd, 0xcf, 0x19, 0x66, 0x78, 0xab, 0x95, 0x24, 0x6d, 0xd9, 0x4b, 0xb8,
	0xdc, 0xe4, 0xdf, 0x22, 0x71, 0x81, 0x28, 0x3a, 0x8a, 0x84, 0x54, 0x4b, 0xcd, 0xbd, 0xe0, 0x20,
	0xec, 0xcd, 0x1e, 0x4c, 0xcb, 0x95, 0xf7, 0x0e, 0x98, 0xfc, 0xf4, 0xe0, 0xbc, 0x26, 0x67, 0x43,
	0x68, 0xcb, 0xa5, 0x50, 0x51, 0x82, 0xdc, 0x0b, 0xfc, 0xb0, 0xfb, 0xf6, 0xf0, 0xc7, 0x1b, 0xbf,
	0xe3, 0xb1, 0x21, 0x1c, 0x9b, 0xc8, 0xe6, 0xea, 0x08, 0xdd, 0xd8, 0x0f, 0xbc, 0xb0, 0xcb, 0x5e,
	0xc1, 0xb8, 0xba, 0x41, 0x4a, 0x11, 0xa5, 0x42, 0xaa, 0x2f, 0x16, 0xd3, 0x94, 0x1f, 0x04, 0x5e,
	0xd8, 0x9b, 0x0d, 0x2b, 0x2b, 0xbc, 0x93, 0x16, 0x63, 0x92, 0x5a, 0xb1, 0x9b, 0x7f, 0xd7, 0x77,
	0x65, 0x74, 0xdd, 0xd6, 0x7d, 0xdd, 0xc9, 0x2d, 0x5c, 0xd4, 0x4b, 0x5f, 0x00, 0xaf, 0xdf, 0x68,
	0x7f, 0x11, 0x56, 0x51, 0xde, 0xe5, 0xe3, 0xc9, 0xaf, 0x16, 0x9c, 0xfd, 0x97, 0xb2, 0x31, 0xf4,
	0x9d, 0x4b, 0x65, 0xc9, 0x1c, 0x6d, 0x71, 0x92, 0xc1, 0xee, 0x24, 0x23, 0xe8, 0xb8, 0xa1, 0x5c,
	0x70, 0xbf, 0x3c, 0x78, 0x0a, 0x63, 0x83, 0xd1, 0x4a, 0xcc, 0xb3, 0xe5, 0x12, 0xad, 0xd0, 0x71,
	0x9c, 0x99, 0x48, 0xc5, 0x5b, 0x31, 0xdf, 0x12, 0xe6, 0x37, 0xd9, 0xb1, 0x81, 0xc7, 0x9e, 0xc1,
	0xc3, 0x7a, 0xd6, 0xa0, 0x8d, 0x51, 0x51, 0x71, 0x85, 0x3d, 0x3d, 0x84, 0xb6, 0x89, 0xe2, 0x15,
	0x52, 0xca, 0x0f, 0x03, 0x3f, 0x6c, 0x15, 0x39, 0xf7, 0xd8, 0x05, 0x1c, 0xe9, 0x98, 0xf2, 0xf8,
	0xa8, 0x1c, 0x07, 0x70, 0x46, 0x91, 0x5c, 0x8b, 0x85, 0xd5, 0x46, 0xec, 0x8a, 0xed, 0x32, 0xf1,
	0x08, 0x4e, 0xff, 0x12, 0x7f, 0x14, 0x9d, 0x32, 0xf0, 0x04, 0xb8, 0xc5, 0x45, 0xc5, 0x20, 0x62,
	0xbd, 0xd6, 0x56, 0x3c, 0xe7, 0xdd, 0x32, 0xf8, 0x18, 0x46, 0x7b, 0xd0, 0x89, 0xf6, 0x1c, 0x34,
	0x13, 0x5e, 0xf1, 0x5e, 0x23, 0xe1, 0x15, 0xef, 0x37, 0x13, 0xce, 0xf8, 0xa0, 0x91, 0x70, 0xc6,
	0x8f, 0x9b, 0x09, 0xaf, 0xf9, 0x49, 0x23, 0xe1, 0x35, 0x3f, 0x2d, 0x71, 0x37, 0xaf, 0x61, 0xf0,
	0x55, 0x19, 0x2b, 0xf2, 0xbf, 0x5b, 0xe0, 0x77, 0x62, 0xa3, 0xe9, 0xc7, 0x4c, 0x49, 0x83, 0xf6,
	0x13, 0xd2, 0x37, 0x6d, 0x57, 0xe9, 0x1d, 0xaa, 0x54, 0xdb, 0x94, 0x9f, 0x14, 0x4f, 0x7e, 0x50,
	0x79, 0x9f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x03, 0xba, 0xba, 0xe6, 0x16, 0x04, 0x00, 0x00,
}
